lib/MetaCPAN/Web/Controller/Login.pm
root/account/identities.html
root/account/openid-login.html
root/static/less/login.less
root/static/less/style.less
root/wrapper.html

Front-end part the of OpenID stuffs. :D

Login via OpenID

---

root/preprocess.html

See https://github.com/CPAN-API/github-meets-cpan/issues/8

github-meets-cpan URL has changed

---

root/inc/twitter/author.html
root/inc/twitter/module.html
root/inc/twitter/release.html

Fix attribute name: s/value=/content=/
Because of: http://validator.w3.org/check?uri=https%3A%2F%2Fmetacpan.org%2Frelease%2FNet-Disqus&charset=%28detect+automatically%29&doctype=Inline&group=0

Twitter cards: fix HTML tags

---

lib/MetaCPAN/Web/Controller/Feed.pm

See https://github.com/CPAN-API/metacpan-web/issues/1488

Using https for items at /feed/recent

---

lib/MetaCPAN/Web/Controller/Feed.pm
root/wrapper.html

Fix the feed URL and URLs in the feed itself to always use `https://` instead of `http://`.

Feed url as https://

---

.tidyallrc
root/static/js/cpan.js

This should address the issue of untidy JS which came up with the merge earlier today.

Set JS tidy defaults + tidy

---

root/static/less/syntaxhighlighter.less

Underline links in POD

---

root/static/js/toolbar.js

Fix sidepanel stickyness

---

root/diff.html

Add link to diff full distribution

---

root/browse.html
root/inc/breadcrumbs.html
root/inc/keyboard_shortcuts.html
root/inc/release-info.html
root/pod.html
root/source.html
root/static/js/cpan.js
root/static/js/github.js

some hot key usability improvements and additions.
#NYPerlHackathon

Improve hotkeys

---

root/static/js/github.js

fixes runtime error on pod source and possibly other pages

add element exists check for pages with no githuburl

---

root/static/js/cpan.js
root/wrapper.html

This means pages that don't show favourit data and do not
change can be cached forever, next step is to do the same for
favourit data.

Switch the Sign in/Account menu from server to client side

---

root/about.html

it's 2015, why talk about 2013?

Keep year references current.

---

root/inc/favorite.html
root/static/css/user.css
root/static/js/cpan.js
t/html.t

Switch personalisation around favourites to javascript instead of server side. This will mean we can cache stuff for longer

switch favs to client side

---

root/static/js/cpan.js

If the user has cookies set to ask every time, accessing localStorage
will throw an exception.  Work around this by shim that just stores the
data for the current page view.
Fixes #1558

work around Firefox bug where localStorage can throw an exception

---

root/inc/module-install.html
root/release.html

Fixed the install template issue for release

fix #1547 added in code to release

---

lib/MetaCPAN/Web/Model/API/Release.pm

also show LICENCE file in distribution file list

---

lib/MetaCPAN/Web/View/HTML.pm
root/inc/perlybook.html
root/inc/release-info.html
root/inc/release-tools.html
t/controller/shared/release-info.t

and other things used in querystrings.
refs #1577.

URI-escape dist name in sidebar links

---

root/release.html

Move changes to top of release page. Fixes #1510.

---

lib/MetaCPAN/Web/Model/API/Changes.pm
t/model/changes.t

link P5#01234 to rt.perl.org in changes

---

root/release.html
root/static/less/release.less

Per the discussion for #1588, I have put the whatsnew section in a well and added a margin to prevent it from overlapping with the right panel.

Make what's new stand out with a well and margin.

---

root/home.html
root/static/css/jquery.autocomplete.css
root/static/js/cpan.js
root/static/less/global.less
root/static/less/home.less
root/static/less/release.less
root/static/less/responsive.less
root/static/less/style.less
root/wrapper.html

This revises the CSS and markup for the search box and home page to closer match normal Bootstrap 3 norms, and fixes some layout issues along the way.
Fixes #1605 and #1606.

Search box and home css/markup revisions

---

root/home.html
root/inc/account-bar.html
root/inc/dependencies-graph.html
root/inc/dependencies.html
root/inc/module-install.html
root/inc/release-tools.html
root/static/js/cpan.js
root/static/less/release.less
root/wrapper.html
t/controller/pod.t
t/controller/release.t

This tries to reduce the chance of having conflicting ids between pod content and the rest of the site.  Includes some other miscellaneous fixes and cleanups.

Reduce id conflicts and other cleanups

---

root/home.html

Thic commit can be reverted once it is no longer required.

Adds a QAH sponsorship request.

---

root/static/js/cpan.js

This is to fix the title attribute of the ++ buttons.

Add setFavTitle in several places. Untested.

---

root/home.html

This reverts commit be110418d93e6138a0b851b957e2d22a1940907e.

Revert "Adds a QAH sponsorship request."

---

lib/MetaCPAN/Web/Controller/Pod.pm

allow mailto and irc links in pod content

---

lib/MetaCPAN/Web/Controller/Author.pm

fix ES query results reading (single values wrapped in arrayref)

---

lib/MetaCPAN/Web/Model/API/Favorite.pm

fix queries for plussers

---

lib/MetaCPAN/Web/Controller/Source.pm

ES output format fix, takes care of both #1703 & #1704

fix issues GH1703 + GH1704

---

README.md
lib/MetaCPAN/Sitemap.pm
lib/MetaCPAN/Web/Controller/Root.pm
metacpan_web.conf
root/about.html
root/about/sponsors.html
root/author.html
root/inc/module-install.html
root/wrapper.html

probably doesn't cover all the issues we have, but will be easier to control from one config (for the templates) + some cleanup.
this is marked WIP - so feel free to comment/correct/patch

[WIP] use config for links where possible

---

lib/MetaCPAN/Web/Model/API/Release.pm

refine release's modules search

---

root/browse.html

fix directory listing

---

lib/MetaCPAN/Web/Controller/Feed.pm

use relative links in feed

---

root/about.html
root/author.html
root/static/opensearch.xml

should replace https://github.com/CPAN-API/metacpan-web/pull/1737

Fix/links2 - make relative an explicit for new domain

---

lib/MetaCPAN/Web/Controller/Release.pm

add missing abstracts in Release page

---

lib/MetaCPAN/Web/Controller/Pod.pm

Fixes #1745.
Requires metacpan/metacpan-api#506.

use local links in pod

---

root/author.html

per https://github.com/metacpan/metacpan-api/issues/502 + #1692

author page: cpan/backpan counts + backpan-only message

---

lib/MetaCPAN/Web/Controller/Release.pm
root/release.html

move code from template to the controller module

---

README.md
lib/MetaCPAN/Web/Controller/Root.pm
metacpan_web.conf
root/browse.html
root/pod.html
root/release.html

Begin using st.aticpan.org

---

metacpan_web.conf
root/about/faq.html
root/static/js/contributors.js

Think this might help with the github authenticaion

rename api-v1.mc.org to fastapi.mc.org

---

lib/MetaCPAN/Web/Controller/Release.pm

Code originally migrated from template. attempt to cut a corner was buggy.
This makes it a bit more accurate, but this code still need some love.
At least now the page will look like it does in v0.

controller/release: correct categories logic

---

lib/MetaCPAN/Web/Controller/Release.pm

fix warning: check uninitialized value

---

root/about/development.html

Fixing link to DEVELOPMENT.md

---

lib/MetaCPAN/Web/Model/API/Lab.pm

not properly tested, but the query seems to work now.
it's broken anyway so I don't see any risk in merging - let's just wait till tests pass.

lab/dashboard: update ES query to work on v1

---

root/inc/release-info.html

The former cpants.charsbar.org is broken, cpants seems to have been removed there.
Fixes #1849

link Kwalitee to cpanauthors.org release info page

---

root/author.html

display full name of profile for alt and title

---

.travis.yml
root/release.html

The wording of the Changes ("Show more/hide more") was a bit confusing.

Show less is the opposite of show more.

---

lib/MetaCPAN/Web/Controller/Activity.pm
lib/MetaCPAN/Web/Model/API/Release.pm

A quick fix to terms that are currently not matching anything.
Next, these queries will be moved to the API.

Activity: fix query terms

---

lib/MetaCPAN/Web/Controller/Author.pm
lib/MetaCPAN/Web/Controller/Feed.pm
lib/MetaCPAN/Web/Model/API/Release.pm

Replace Elasticsearch query with a use of the new API endpoint.

Use new /release/latest_by_author endpoint

---

lib/MetaCPAN/Web/Controller/Source.pm
lib/MetaCPAN/Web/Model/API/File.pm

Replace the Elasticsearch query sending with a call to the new
API endpoint.

Use new /file/dir/PATH API endpoint

---

lib/MetaCPAN/Web/Controller/Author.pm
lib/MetaCPAN/Web/Model/API/Release.pm

Replace the Elasticsearch query sending with a call to the new
API endpoint.

Use new /release/all_by_author/PAUSEID API endpoint

---

lib/MetaCPAN/Web/Controller/Recent/TopUploaders.pm
lib/MetaCPAN/Web/Model/API/Release.pm

Replace sending query with use of the new API endpoint.

Use new /release/top_uploaders API endpoint

---

lib/MetaCPAN/Web/Model/API/Permission.pm

Replace queries send from WEB with calls to the new API
endpoints.

Use new permission API endpoints

---

lib/MetaCPAN/Web/Model/API/Favorite.pm

~~~Note: this can only be merged after the merge & deploy of https://github.com/metacpan/metacpan-api/pull/686~~~

Replace query sending with API endpoint call

---

lib/MetaCPAN/Web/Controller/Search.pm
lib/MetaCPAN/Web/Controller/Search/AutoComplete.pm
lib/MetaCPAN/Web/Model/API/Author.pm

Replace query sending with endpoint usage.

Use new /author/search API endpoint

---

lib/MetaCPAN/Web/Model/API/Release.pm

The use of the no_latest method ws removed in aab539ffc8

Removed unused method

---

lib/MetaCPAN/Web/Controller/Search.pm
t/controller/search/precision.t

Trim leading and trailing whitespace from search query

---

lib/MetaCPAN/Web/Controller/Feed.pm
lib/MetaCPAN/Web/Controller/Release.pm
lib/MetaCPAN/Web/Model/API/Release.pm
lib/MetaCPAN/Web/Role/ReleaseInfo.pm
t/model/release.t

This time without breaking it off the async api.

Use /release/versions API endpoint

---

lib/MetaCPAN/Web/Model/API/Lab.pm

Use new /release/by_author API endpoint

---

lib/MetaCPAN/Web/Controller/Mirrors.pm
lib/MetaCPAN/Web/Model/API/Mirror.pm

Use new /mirror/search API endpoint

---

lib/MetaCPAN/Web/Model/API/Favorite.pm

Use /favorite/agg_by_distributions API endpoint

---

lib/MetaCPAN/Web/Controller/Recent/TopUploaders.pm
lib/MetaCPAN/Web/Model/API/Author.pm

Replace query sending with a call to the new API endpoint.

Use /author/by_ids API endpoint

---

lib/MetaCPAN/Web/Model/API/Rating.pm
lib/MetaCPAN/Web/Role/ReleaseInfo.pm

Use /rating/by_distributions API endpoint

---

lib/MetaCPAN/Web/Model/API/Changes/Parser.pm

Make sure we actually got a usable date before using it, and be a bit
more flexible in the accepted formats.
Fixes #1962 and metacpan/metacpan-api#735.

improve changelog date parsing

---

README.md

same as https://github.com/metacpan/metacpan-api/pull/771

change badge (png -> svg) and add kritika badge

---

app.psgi
lib/MetaCPAN/Web/Model/API.pm
t/controller/search/autocomplete.t

Adds logging of API requests in debug mode, and a request id to the logging.  The request id is also sent with API requests.

Debug and logging bits

---

lib/MetaCPAN/Web/Controller/River.pm
lib/MetaCPAN/Web/Model/API/Distribution.pm
root/inc/breadcrumbs.html
root/inc/release-table.html
root/inc/river-gauge.html
root/river/gauge.svg
root/search.html
root/static/less/global.less
root/static/less/search.less
root/static/less/table.less
t/controller/author.t

Affects the search results, the release page and all documentation pages
under a release, and all tables of releases (recent page, author page,
reverse dependencies, etc).
Resolves GH#1679.

Show the River of CPAN position for distributions

---

root/static/js/github.js

We request 15 issues and display up to 15 issues, but the text
is hard-coded to "Last 15 issues" where there can be less
than 15 returned.

Modified GH issues box text

---

.perltidyrc
app.psgi
bin/purge.pl
lib/MetaCPAN/Sitemap.pm
lib/MetaCPAN/Web/Controller/Account/Turing.pm
lib/MetaCPAN/Web/Controller/Author.pm
lib/MetaCPAN/Web/Controller/Changes.pm
lib/MetaCPAN/Web/Controller/Diff.pm
lib/MetaCPAN/Web/Controller/Favorite.pm
lib/MetaCPAN/Web/Controller/Lab.pm
lib/MetaCPAN/Web/Controller/Mirrors.pm
lib/MetaCPAN/Web/Controller/Permission.pm
lib/MetaCPAN/Web/Controller/Pod.pm
lib/MetaCPAN/Web/Controller/Raw.pm
lib/MetaCPAN/Web/Controller/Recent.pm
lib/MetaCPAN/Web/Controller/Recent/TopUploaders.pm
lib/MetaCPAN/Web/Controller/Release.pm
lib/MetaCPAN/Web/Controller/Requires.pm
lib/MetaCPAN/Web/Controller/River.pm
lib/MetaCPAN/Web/Controller/Root.pm
lib/MetaCPAN/Web/Controller/Search.pm
lib/MetaCPAN/Web/Controller/Source.pm
lib/MetaCPAN/Web/Model/API/Favorite.pm
lib/MetaCPAN/Web/Model/API/Lab.pm
lib/MetaCPAN/Web/Model/API/Permission.pm
lib/MetaCPAN/Web/Model/ReleaseInfo.pm
lib/Plack/Middleware/Session/Cookie/MetaCPAN.pm
t/controller/account.t
t/controller/feed.t
t/lib/MetaCPAN/Web/Controller/Test.pm

enable perltidy --weld-nested-containers

---

root/wrapper.html

Currently looks like:
If someone has pointers to improve the styling, I'm all ears.

Add stickeryou as a site sponsor

---

root/source.html

Don't hide pod in source view if there is only a small amount of code

---

lib/MetaCPAN/Web/Controller/Release.pm

We already have /source/AUTHOR/RELEASE/FILE but that requires the
specific author and version of the release.
The URL is under /release/DIST/source because it can't fit under
/source/ given the way that already works.

add /release/DIST/source/FILE endpoint

---

root/wrapper.html

Add a link to our s.c.o. blog post

---

root/about/meta_hack.html
root/home.html

Add sponsors for meta::hack 3

---

lib/MetaCPAN/Web/Controller/Pod.pm
lib/MetaCPAN/Web/Model/API/Release.pm
lib/MetaCPAN/Web/Model/ReleaseInfo.pm
root/inc/release-info.html
t/controller/pod.t

Fixes #1678 
This is blocked by https://github.com/metacpan/metacpan-api/pull/863

Add cpancover.com links

---

root/home.html

At this point we only have a single hint,
move it as a "title" for the "I'm Feeling Lucky"
button.
We can consider restoring the previous logic
once we have more than one hint listed.

Move the hint as a button title

---

root/wrapper.html

Reverts metacpan/metacpan-web#2146

Revert "Remove stickeryou from footer"

---

cpanfile
cpanfile.snapshot

This squashes a startup warning when firing up the web app in a terminal
window

Add Term::Size::Any to cpanfile

---

root/release.html

remove extra whitespace

---

root/home.html

Remove PerlCon 2019 advertisement

---

root/inc/author-pic.html

remove remaining google plus links

---

lib/MetaCPAN/Web/Controller/Pod.pm
lib/MetaCPAN/Web/Model/ReleaseInfo.pm
root/inc/notification.html
root/pod.html
root/release.html
root/static/less/notification.less
root/static/less/style.less

A notification will display at the top of the page in /release and /pod if ADOPTME, HANDOFF or NEEDHELP is found as an author within the modules permissions.

highlight modules or dists with ADOPTME or HANDOFF or NEEDHELP

---

root/inc/notification.html

In template toolkit it is array.0.key and not array[0].key
Closes #2232

broken mailto link - Looking for help! <ARRAY(0xcde66a0)>

---

lib/MetaCPAN/Web/Model/API.pm

Fixes #2027 Can't disconnect any identities

Make sure DELETE calls to the API include query params

---

root/about/sponsors.html

Sorry, this could've been one MR had I been more detail oriented! ;-)

sponsors: remove background color from Fastmail logo

---

lib/MetaCPAN/Web/Model/ReleaseInfo.pm
root/inc/breadcrumbs.html
root/inc/release-info.html

Fix for version display in version jump list; uses version from download field.

---

root/inc/dependencies.html
root/static/js/cpan.js
root/static/js/jquery.tablesorter.js
run-dev
t/controller/shared/release-info.t

Fixes a couple issues with the javascript, including having Reverse dependencies override a user trying to cmd+click to open a new tab, and sortable tables often being broken.

Fix some errors in the javascript

---

root/static/js/bootstrap-slidepanel.js
root/static/js/toolbar.js
root/static/less/bootstrap-slidepanel.less
root/static/less/nav-list.less
root/wrapper.html

I have tested a few pages on desktop and android(mobile) with Firefox, and Firefox nightly.

Improve mobile interface

---

cpanfile
cpanfile.snapshot
lib/MetaCPAN/Web/Controller/Feed.pm
lib/MetaCPAN/Web/Role/Request.pm
t/controller/account.t
t/controller/search.t
t/controller/search/autocomplete.t
t/encoding.t

XML::Feed is heavier, has some odd bugs, and has prerequisites that are currently broken.

use XML::FeedPP for feed generation

---

root/home.html

Partly address #2311 as part of HSTS, which is otherwise being taken care of by @haarg at the Fastly level.

rel=canonical for front page too

---

root/inc/author-pic.html
root/wrapper.html

Per https://www.webpagetest.org/result/200701_40_82038f60f5c208b84dea00edd39a09c5/ there was still room for improvement:
- Performance 91
- Accessibility 60
- Best practices 77
- SEO 82
This aims to improve most of those.

Tweaks to improve Lighthouse score

---

app.psgi

This is the fix I proposed, and would therefore close #2256

Warn handler check $logger true before method call

---

lib/MetaCPAN/Web/Controller/Account.pm
t/controller/account.t

Validate asciiname in profile

---

lib/MetaCPAN/Web/Controller/Feed.pm
lib/MetaCPAN/Web/Controller/Permission.pm
lib/MetaCPAN/Web/Controller/Pod.pm
lib/MetaCPAN/Web/Controller/Source.pm
lib/MetaCPAN/Web/Model/API/Changes/Parser.pm
lib/MetaCPAN/Web/Model/API/Favorite.pm
lib/MetaCPAN/Web/View/HTML.pm
log4perl_prod.conf

Following on from #2286, this PR is intended to suppress all the errors in the most recent log I've seen.

More log tidying

---

lib/MetaCPAN/Web/RenderUtil.pm

See this FB discussion to see why I've done this.
https://www.facebook.com/groups/perlprogrammers/permalink/3393568844009213/

Added colspan and rowspan to the list of TD attributes

---

lib/MetaCPAN/Web/Controller/Permission.pm
lib/MetaCPAN/Web/Model/API.pm
lib/MetaCPAN/Web/Model/API/Permission.pm
root/inc/permission.html
root/permission/distribution.html
root/permission/module.html
t/model/permission.t

Refactor the permissions model methods, and normalize their return
values.
Refactor the permissions controller to not have weird conditionals.
Reorganize notification code so it could be used for multiple modules.

refactor and fix permissions handling

---

lib/MetaCPAN/Web/Model/API/Permission.pm
t/model/permission.t

handle authors with multiple emails

---

lib/MetaCPAN/Web/Controller/Pod.pm
lib/MetaCPAN/Web/Model/API/Diff.pm
lib/MetaCPAN/Web/View/HTML.pm
t/controller/search/autocomplete.t

Yesterday's error log contained 15 lines in total. This fixes those.

Suppress more errors

---

cpanfile
cpanfile.snapshot
lib/MetaCPAN/Sitemap.pm
lib/MetaCPAN/Web/Controller/Feed.pm
lib/MetaCPAN/Web/Controller/Permission.pm
lib/MetaCPAN/Web/User.pm
lib/Plack/Middleware/Assets/Core.pm
t/controller/account.t
t/model/permission.t
t/moose.t

and apply the new tidier to Perl files

Bump Perl::Tidy from 20190915 to 20201001

---

lib/MetaCPAN/Web/Controller/Account.pm

Maybe purge Fastly cache after author profile updated

---

root/account/profile.html
root/static/less/author.less

link to gravatar for changing avatar

---

root/release.html

fix condition for showing pod link on examples

---

root/home.html

This link needs to be removed at the end of January 2021

TPF support for new developers survey

---

root/home.html

No end date specified in the comments due to the current situation. Worth putting front and centre as this has not been well communicated as far as I can tell.
References:
https://perl.topicbox.com/groups/infrastructure/Te92859202f730470
https://www.nntp.perl.org/group/perl.perl5.porters/2021/01/msg258825.html

add rt.cpan sunset notice

---

root/home.html

As mentioned in https://github.com/metacpan/metacpan-web/pull/2422

rewording of rt.cpan notice

---

root/home.html

@oalders @haarg Thanks for having the survey here - it can now be removed.

TPF survey - remove

---

root/home.html

Also, switch from danger to alert.

Reword RT shutdown banner

---

root/home.html
root/static/js/cpan.js
root/wrapper.html

Hopefully this will help more people to know about the shortcuts - #2440

add button with question-mark to bring up the modal window

---

lib/MetaCPAN/Web/Controller/Diff.pm
lib/MetaCPAN/Web/Model/API/Diff.pm
root/diff.html

The data from the API for diffs is not in the best form. Eventually that
should get fixed, but for now move some logic into the model layer
rather than the template.

clean up diff model to provide more reasonable data to template

---

root/inc/author-pic.html
root/static/less/breadcrumbs.less

They aren't really paragraphs, so use div tags to have more natural
markup. Apply margin using CSS rather than relying on <p> tag.
Also remove trailing period from non-pause user count to be consistent with
pause user count.

use divs to lay out plusser lines rather than p

---

root/search.html
root/static/less/search.less
t/controller/search.t
t/controller/search/precision.t

Use more semantic tags and CSS for search page layout. The result is a
couple pixels different, but it's not a meaningful difference.

improve markup of search page

---

root/base.tx

This was broken by #2490.
Fixes #2505

fix hamburger menu not appearing

---

root/account/profile.tx
root/browse.tx
root/pod.tx
root/source.tx

FontAwesome has solid and outline variants for most of its icons. We are
using the solid variant for nearly every icon.
Change the remaining few icons from outline to solid for increased
visual consistency.

always use solid icons

---

root/static/less/account.less

The icons are not currently appearing in the edit profile page, I think this is what needs to be added.

Add png icons for accounts for edit profile page

---

root/base/release.tx

Add bus factor to left panel

---

root/static/less/nav-list.less

Make sure the left panel displays on top of other content when it is
positioned.

left panel should be on top

---

root/base/release.tx

fix raw browse link

---

root/static/js/syntaxhighlighter.js

This updates the URLs generated by the syntax highlighter to match the
URLs used by the test of the site after PR#2512.
It also fixes how it recognises if a source or pod page is being
displayed. Previously it was using the URL of the current page, but it
will now be based on recognising the full page source view, the same as
is used to show line numbers and other features.

fix links generated by syntax highlighter

---

root/account/identities.tx

- Make copy around available identities a bit clearer

Make copy around available identities a bit clearer

---

app.psgi
bin/purge.pl
lib/MetaCPAN/Middleware/Static.pm
lib/MetaCPAN/Sitemap.pm
lib/MetaCPAN/Web/ActionRole/Sortable.pm
lib/MetaCPAN/Web/Controller/Account.pm
lib/MetaCPAN/Web/Controller/Changes.pm
lib/MetaCPAN/Web/Controller/ContributingDoc.pm
lib/MetaCPAN/Web/Controller/Feed.pm
lib/MetaCPAN/Web/Controller/Pod.pm
lib/MetaCPAN/Web/Controller/Search.pm
lib/MetaCPAN/Web/Model/API.pm
lib/MetaCPAN/Web/Model/API/Changes.pm
lib/MetaCPAN/Web/Model/API/Diff.pm
lib/MetaCPAN/Web/Model/API/File.pm
lib/MetaCPAN/Web/Model/API/Module.pm
lib/MetaCPAN/Web/RenderUtil.pm
lib/MetaCPAN/Web/Test.pm
lib/MetaCPAN/Web/Test/HTML5/Element/SVG.pm
t/controller/account.t
t/controller/feed.t
t/controller/home.t
t/controller/release.t
t/controller/robots.t
t/controller/search.t
t/model/permission.t
t/model/release.t
t/session.t
t/view/json.t

Experimenting with:
perlnitpick --rules QuoteSimpleStringWithSingleQuote

Requote some vars

---

root/static/less/pod.less

I create the pull request about "Table CSS" #2623

Add the design of pod tables

---

root/pod.tx

fix browse link for pod files in dist root

---

root/about/contact.tx

- Remove Facebook from contact page
- Discourage inappropriate emails to noc

Update copy on contact page

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

- Don't allow issues to be created which do not have a template
- Add a feature request template

Add a feature request issue template

---

root/home.tx

TPRC is over, let's remove the advertising.
This reverts commit ff5d8ede432aa27f5bd0cb366d14f83da571fefc.

Revert "Advertise TPRC 2022 on HomePage"

---

README.md

- Remove Kritika badge from README
- Update some instructions for local development outside of Docker

Update some instructions for local development outside of Docker

---

.github/workflows/staging.yml

- Run staging workflow on pushes to "staging" branch
- Tag staging images with SHA of staging branch HEAD

Tag staging images with SHA

---

root/about/sponsors.tx

Add paragraph for Deriv sponsor!  :tada: :man_dancing: :muscle: :camel:

Add sponsor paragraph for Deriv.

---

root/author.tx

don't create links to profiles with no id on author page

---

lib/MetaCPAN/Web/Controller/Account.pm
lib/MetaCPAN/Web/RenderUtil.pm
lib/MetaCPAN/Web/View/Xslate/Bridge.pm
root/static/js/cpan.js

This provides the user's avatar in the login_status end point, to allow it to be displayed on the account button.
Hard coding the size in this location is not ideal, but improving that can be left to later.

Provide avatar though login_status end point

---

root/base/release.tx
root/static/js/cpan.js
root/static/js/dropdown.js
root/static/less/account.less
root/static/less/author.less
root/static/less/bootstrap-slidepanel.less
root/static/less/breadcrumbs.less
root/static/less/diff.less
root/static/less/global.less
root/static/less/home.less
root/static/less/log.less
root/static/less/nav.less
root/static/less/print.less
root/static/less/responsive.less
root/static/less/style.less

This cleans up some bits in the less code. Some whitespace cleanups, removing some unused code, and removing some needless use of mixins. Also removes a problematic use of the extend feature that would be hard to adapt to any other CSS templating system.

cleanups of less code and other misc

---

root/base.tx
root/home.tx
root/static/less/global.less
root/static/less/home.less
root/static/less/nav.less
root/static/less/responsive.less

Add temporary banner

---

app.psgi

Add some additional headers to the Log4Perl MDC, which can be used for additional filtering.
For example, filters can be defined like:
log4perl.filter.DocOnly = Log::Log4perl::Filter::MDC
log4perl.filter.DocOnly.KeyToMatch = Sec-Fetch-Dest
log4perl.filter.DocOnly.RegexToMatch = document
log4perl.filter.IsBrowser = Log::Log4perl::Filter::MDC
log4perl.filter.IsBrowser.KeyToMatch = Sec-Fetch-Dest
log4perl.filter.IsBrowser.RegexToMatch = .
log4perl.filter.OnlyDocFromBrowser = Log::Log4perl::Filter::Boolean
log4perl.filter.OnlyDocFromBrowser.logic = DocOnly || !IsBrowser
The OnlyDocFromBrowser filter can then be added to an appender:
log4perl.appender.OUTPUT.Filter = OnlyDocFromBrowser
This would then silence any logging from requests for things like images or XHR requests, which can help when …

Log4Perl MDC: add additional headers

---

lib/MetaCPAN/Web/Model/API/Changes.pm

The order needs to be correct so we can find the dev releases that came before the current version.

fix sort order of parsed changes

---

root/author.tx

Add repology link to sidebar on author page

---

root/home.tx

This year the North American Conference
is in Toronto from July 11 to 13th.
More information on tprc.to website.

Advertise TPRC 2023 on HomePage

---

.github/workflows/test.yml

Use perl-actions/install-with-cpm@stable

Use perl-actions/install-with-cpm@stable

---

lib/MetaCPAN/Web/Role/FileData.pm

As seen in e.g. [CPAN-Meta-Requirements](https://metacpan.org/release/RJBS/CPAN-Meta-Requirements-2.141-TRIAL/source/CONTRIBUTING.mkdn).

Recognise .mkdn files as Markdown

---

bin/generate_sitemap.pl
bin/purge.pl
git/hooks/pre-commit
lib/MetaCPAN/Web/Role/FileData.pm
lib/MetaCPAN/Web/View/Xslate/Bridge.pm
perlimports.toml
t/controller/account.t
t/lib/MetaCPAN/Web/Controller/Test.pm
t/model/permission.t

- perlimports should ignore Test::More
- perlimports -i t
- perlimports -i web
- perlimports should ignore namespace::clean

perlimports

---

lib/MetaCPAN/Web/View/Xslate/Bridge.pm

fix gravatars

---

root/base.tx
root/static/less/footer.less

Remove yellow bot from footer

---

.github/workflows/update-snapshot.yml

This also fixes the token variable being used.

align snapshot updating with api

---

root/static/js/cpan.js
root/static/less/pod.less

Move index-container to top of page on smaller screens

---

t/static-files.t

find may include things like swap files, and sort is locale dependent. It's more reliable to implement the regeneration ourselves.

add regeneration to static-files.t test

---

root/base.tx

Add sponsor banner for Perl Toolchain Summit

---

root/static/less/author.less

Remove fixed height

---

.github/workflows/build-production-container.yml

Depends on metacpan/metacpan-k8s#98, and will be required once it is merged.

call set-image with base and full tag

---

root/static/js/cpan.js
root/static/js/inject.js
root/static/js/syntaxhighlighter.js

This fixes #3062 as well as several other unreported issues.

fix various onclick handlers by explicitly attaching functions to window

---

root/static/less/nav.less

Center fa-icons

---

root/diff.tx

fix "Diff full distribution" reversing diff

---

root/static/less/search.less

Align magnifying glass

---

docker-compose.yml

fix docker compose paths

---

lib/MetaCPAN/Web/Controller/About.pm

contributors: only route with no parameters

---

root/base/release.tx

Hi Team,
Please review the pull request.
Added Kwalitee score svg image next to the Kwalitee link.
https://metacpan.org/pod/PGObject::Util::DBAdmin
Many Thanks.
Best Regards,
Mohammad

Proposed patch for issue 2912

---

cpanfile
cpanfile.snapshot

Use new MetaCPAN::Role version
Seems like a lot of cpanfile.snapshot changes but I guess as long as all tests have run

Update cpanfile with MetaCPAN::Role 1

---

lib/MetaCPAN/Web/Model/ReleaseInfo.pm
root/inc/favorite.tx
root/static/js/cpan.js
t/controller/shared/release-info.t

Reverts metacpan/metacpan-web#3380
Now that traffic appears to be under control, let's try this again.

Revert "Remove favourite function - causing traffic"

---

root/about/faq.tx

Recently I had a little confusion with the identities disconnect. Does this patch make the corresponding FAQ entry better?

faq.tx: Clarify how to merge accounts
