metacpan/metacpan-web

- root/about/faq.html
- root/author.html
- root/browse.html
- root/diff.html
- root/inc/release-tools.html
- root/pod.html
- root/release.html
- root/source.html
- root/wrapper.html
- t/controller/shared/release-info.t
I noticed some pages on metacpan use http instead of https where there are https links available.
This PR changes the links to api.metacpan.org, explorer.metacpan.org and perl.org to use https.
> Use https where possible

- lib/MetaCPAN/Web/Model/API/Favorite.pm
A small fix for #1430 , I'm not sure if it's the right fix though. Since we get the number of non-PAUSE user from total_plussers - PAUSE_user = non-PAUSE . I'm not sure why number of users with PAUSE id who ++ed the module sometimes it's more than number of total plussers. I guess that because those PAUSE users don't register for a user id with MetaCPAN?   So, I just assume that if the number of PAUSE users more than total plusser then just assume that nobody is non-PAUSE user can set 0 number. Please just close this PR if I'm wrong.
> Set 0 to non-PAUSE user

- lib/MetaCPAN/Web/Controller/Pod.pm
This addresses the issue <https://github.com/CPAN-API/metacpan-web/issues/935>.
| Page | Before | After |
|--------|----------|--------|
| [Test::podimage](https://metacpan.org/pod/Test::podimage) | <img src="https://cloud.githubusercontent.com/assets/94489/6205340/31aba502-b530-11e4-9e5f-fbc88e4e3e38.png" width="300" />  | <img src="https://cloud.githubusercontent.com/assets/94489/6205343/4572ecd0-b530-11e4-843d-1dd854f1aaa4.png" width="300" /> |
| [IPerl example](https://metacpan.org/pod/release/ZMUGHAL/Devel-IPerl-0.002/example/20150209_IPerl_display_demo.pod) | <img src="https://cloud.githubusercontent.com/assets/94489/6205345/54cca8b0-b530-11e4-81b2-b5a89bbfaa91.png" width="300" />   | <img src="https://cloud.githubusercontent.com/assets/94489/6205346/5cb4bc8e-b530-11e4-87d6-0c15bec7a …
> add explicit data: URI scheme support for use in images

- lib/MetaCPAN/Web/Controller/Feed.pm
The links in the news feed don't match the associated IDs on the news page. This commit fixes that.
Third attempt. Sorry about that :-/
> Fix links in news feed.

- lib/MetaCPAN/Web/Model/API/Release.pm
.pod files in the root level of a Foo-Bar-Baz distribution are installed into
lib/Foo/Bar/*.pod, which pollutes the installation, so we should not encourage
this practice.
> do not display .pod versions of documentation

- root/wrapper.html
Adding icons to the top menu helps separate the entries from one another and provides a glanceable hint as to what each item is for that can be recognized by many people before actually reading the text.
This is only a crude and untested implementation. I prototyped in the browser and adapted the template to generate what i hope is an equivalent result.
Here's a preview in small and big:
> add icons to the top menu to increase discoverability

- root/wrapper.html
The current item name "Feedback" is very vague, and doesn't make it clear
that behind it the source as well as the bug tracker can be found. By
making it mention Github it draws the eye because of how known it is, and
by making it mention issues (the general language used for bugs on
metacpan) it makes it clear that behind that link the bug tracker can be
found. This might make it easier for people to realize the possibility of
easy contribution and to do so.
> rename top menu entry "Feedback" to "Github Issues" to increase visibility

- root/static/less/nav.less
I have no idea if the code makes sense. If it works right, it should nudge the icons up a little to make the lower border align with the lowest border of the text it's next to.
> make vertical alignment of image-based icons in nav bar nicer-looking

- root/inc/perlybook.html
`&` must be encoded as `&amp;` in href attributes
> perlybook.html: fix URL encoding

- app.psgi
added in cache control as a lot of resources are not cache by the user's browser therefore reloaded form fastly. Also added in source to the list
> added in cache control for 1hr and caching of /source

- root/about/faq.html
- root/wrapper.html
> point links to the API to the up-to-date location

- cpanfile
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- t/controller/shared/release-info.t
This apparently does *not* come from the distribution endpoint.
refs #1577.
> URI escape fabricated RT urls

- lib/MetaCPAN/Web/View/JSON.pm
- t/lib/MetaCPAN/Web/Controller/Test.pm
- t/view/json.t
Ever since we added the `favorites_as_json` thing i've been seeing a 500 Error in my console about it.
I noticed this week that it is actually killing the Account menu for me.
I **am** logged in, but b/c the json call fails, the javascript shows me the "Sign in" menu, which is very confusing.
I noticed an error in the log:
```
[error] Caught exception in MetaCPAN::Web::View::JSON->process "encountered object 'true', but neither allow_blessed, convert_blessed nor all
ow_tags settings are enabled (or TO_JSON/FREEZE method missing) at (eval 891) line 151."
```
and tracked it down to the fact that my user profile has booleans in the "extra" data.
> Json view errors

- .travis.yml
Use newer container-based infrastructure and cache the `local::lib` to save 10 minutes off each build.
> Use containers and build caching on travis

- lib/MetaCPAN/Web/Controller/Account.pm
- lib/MetaCPAN/Web/Role/Request.pm
- lib/MetaCPAN/Web/View/HTML.pm
- root/account/profile.html
- root/preprocess.html
- t/controller/account.t
I believe this fixes #1562.
We're applying the typical utf8 json handling when Catalyst is already doing the en/de-coding, so everything is doubled.
> Fix json/utf8 en/de-coding in profile.extra

- root/about/faq.html
[Reviews](https://chrome.google.com/webstore/detail/metacpan-helper/aoioenbjpmccpkincghhjfmeceknpcnb/reviews) says that old chrome extension does not seem to work. Link to source code is [broken](https://github.com/worr/metacpan-ext).
> Replace MetaCPAN Helper with MetaCPAN redirect

- root/static/js/syntaxhighlighter.js
This lets you select multiple lines in the source view by shift-clicking.
Fixes #1592.
> Multi-line selection in source view

- root/release.html
- root/static/js/cpan.js
- root/static/less/release.less
Adds a link to expand and collapse large whatsnew sections.  The link text is hardcoded to be "Show More" and "Show Less" because I couldn't figure out how/if any internationalization code worked.  Some animation would make this look much nice, but I lack the jQuery/CSS chops for that.
> Add link to expand and collapse long change lists

- root/inc/breadcrumbs.html
- root/inc/rating.html
- root/inc/release-tools.html
- root/pod.html
- t/schema_org.t
This patch fixes the schema.org microdata embedded in the metacpan POD page. The result can be seen in Google's Structured Data Testing Tool - see the screenshot:
Other pages that use the same includes are not affected at all.
I added a unittest to assure that things stay like that :-)
Fixes #1629.
> schema.org markup fixed, unittest added

- root/about/faq.html
Pulling the suggestion of clearing all cookies (including from api.) up out of an issue comment and into the FAQ.  Also changing some headings to hopefully guide people to the appropriate solution more successfully.
Relevant to #1579 #1578 #1005 #996 #636 #566 ... et al.
> Clearer phrasing for fixing accounts with confused identities

- root/inc/author-pic.html
- root/static/less/author.less
The coderwall API for this image seems to break once a year or so.
Nobody on their end notices until I poke them on Twitter, so I assume it
doesn't really get used all that much.  I also don't think people on the
MetaCPAN side really use it either.
> Remove coderwall endorse button.

- root/inc/rating.html
> fixed whitespace if rating was non-integer

- lib/MetaCPAN/Sitemap.pm
- lib/MetaCPAN/Web/Controller/Activity.pm
- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/Controller/Favorite.pm
- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Controller/Recent.pm
- lib/MetaCPAN/Web/Controller/Recent/TopUploaders.pm
- lib/MetaCPAN/Web/Controller/Search.pm
- lib/MetaCPAN/Web/Controller/Search/AutoComplete.pm
- lib/MetaCPAN/Web/Model/API/Author.pm
- lib/MetaCPAN/Web/Model/API/Favorite.pm
- lib/MetaCPAN/Web/Model/API/File.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/API/Rating.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
- lib/MetaCPAN/Web/Role/ReleaseInfo.pm
- lib/MetaCPAN/Web/Util.pm
- root/inc/rating.html
- t/controller/diff.t
- t/controller/search/autocomplete.t
- t/controller/source.t
- t/model/release.t
- t/plack/mcless.t
Some of the hacks used (except for local configuration files) to allow working with ES 2.3 API
I assume this is far from being complete and this PR is only meant for the discussion and change reference for actual future changes.
> [WIP] some hacks to allow working against ES 2.3 index

- lib/MetaCPAN/Web/Controller/Release.pm
- lib/MetaCPAN/Web/Model/API/Changes.pm
- lib/MetaCPAN/Web/Model/API/Changes/Parser.pm
- root/release.html
- root/static/js/cpan.js
- root/static/less/release.less
This causes metacpan to show all changelog entries since the last stable release.  Also fixes the handling of -TRIAL releases, and has a cleanup of the show/hide mechanism.
Fixes #1624 and #1671.
> Show changelogs since last stable

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Web/Controller.pm
- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Controller/Recent.pm
- lib/MetaCPAN/Web/Controller/Search/AutoComplete.pm
- lib/MetaCPAN/Web/Elasticsearch/Adapter.pm
- lib/MetaCPAN/Web/Role/ReleaseInfo.pm
- t/elasticsearch_adapter.t
There is no real need for this to be in a Role, the functionality
does not depend on the object at all and it also makes it hard
to reuse by tests code.
This change moves it into an importable function we can use
where needed.
There are few coming test fixes that depend on it.
> Moved Elasticsearch::Adapter (single_valued_arrayref_to_scalar)

- lib/MetaCPAN/Web/Model/API/Release.pm
We filter out any files in t or xt when separating out where to list
them on the release page.  If these files aren't filtered out in our
intial query, it can inflate the number of results over our 250 limit,
so that files we actually want to display won't be included.
This was the case for https://metacpan.org/release/OCBNET/CSS-Sass-3.3.4.
It has thousands of files in t/ named expected_output.css.  As a result,
most of the files we care about in the root weren't shown.
> exclude t and xt directory from other files at search time

- lib/MetaCPAN/Web/Model/API/Module.pm
solves the missing 'module' object issue in search (and by that the links of `module` name to `pod` page from the search page - issue #1709)
> fix search results (fixes module->pod link in search page)

- root/inc/dependencies.html
- root/pod.html
- root/release.html
- t/controller/shared/release-info.t
There already is a /requires/module/<module> endpoint, so use that on
individual module pages instead of /requires/release/<dist>.
In passing, clean up the variable passing to inc/dependencies.html by
passing the release object, since it uses several fields from it, not
just the dependencies.
> Link to reverse deps for module on module page

- root/browse.html
- root/release.html
- root/source.html
The canonical URLs for release and author info and source browsing don't
have trailing slashes, so avoid an unnecessary redirect roundtrip by
removing them from navigation links.
> Remove erroneous trailing slashes from links

- root/author.html
Update author page to have links to both the author's current CPAN author directory (their releases that are still on CPAN) and their BackPAN directory (all releases ever done).
I often want to look at both of these places, and always end up typing the URLs directly. This will save me some typing :-)
> Have both CPAN author directory link and BackPAN author directory link

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Release.pm
- root/inc/breadcrumbs.html
- root/inc/release-info.html
- root/preprocess.html
When picking release specific vs dist or module links, we should choose based on the URL of the current page rather than the status of the dist.  Even if we are on the latest release of a dist, the links should still be relative to the release if we are on a release specific URL.
For links we generate, control that in the templates.  For links in POD, pass the permalinks parameter as appropriate.
Related to cpan-api/cpan-api#497
> Improved links and better distinction non-latest pages

- root/inc/breadcrumbs.html
don't see a reason why we don't show single backpan items, pretty sure it's a bug.
will merge once all tests pass.
> breadcrumbs: fix minimum backpan count

- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/View/HTML.pm
- root/author.html
another structure being built in the templates moved to the controller.
> author page: moved logic from template to module

- lib/MetaCPAN/Web/Model/API/Changes.pm
If the dist version is not parsable as a version, just do string
comparisons against the versions found in the change log.
Fixes 500 errors on https://metacpan.org/release/WHITEWIND/neverbounce_0_02
> fix latest changes when dist version is unparsable

- root/about/contributors.html
- root/about/development.html
- root/inc/keyboard_shortcuts.html
- root/preprocess.html
- root/static/js/github.js
- root/wrapper.html
Hi all!
This pull-req corrects the capitalisation of "GitHub". It was not tested locally, so please merge after testing or CI. Hacktoberfest was part of my motivation for it, but I bookmarked the typo earlier.
> Correct capitalization of "GitHub".

- lib/MetaCPAN/Web/Controller/Login.pm
- lib/MetaCPAN/Web/Model/API.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/API/User.pm
- t/encoding.t
API->request accepted a hashref of parameters, and in some places they
were used as if they were URL params.  Instead, they only accepted a
method and an access token to use.
Change request to use the parameters as URL query parameters, and use a
separate parameter for the URL.
> change signature on request to allow query params

- lib/MetaCPAN/Web/Model/API/Module.pm
The total will always be the number of documents matched, not the number
of documents returned for the given page.  Instead, do what
search_collapsed does and check if we have any distributions.
Additionally, guard search_descriptions against an empty id list, which
produces invalid queries.
I found these while tracking down the cause of thousands of 500s on
/file/_search, ultimately being triggered by a web crawler.
> Short-circuit correctly in search_expanded

- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
When an author is missing an email, don't die, seed as an empty list.
> Fix undefined deref in author email

- .travis.yml
Attempt to build on 5.22 with cpanfile.snapshot and with out it. This is skipped for 5.18 and 5.20, where it only builds with a base cpanfile
> cpanfile.snapshot builds

- lib/MetaCPAN/Web/Controller/Release.pm
modules is an arrayref that will commonly only have one element.
Flattening it to a single value is incorrect.  The code that determines
how to link modules is expecting an arrayref.
Removing the flattenning doesn't seem to cause any issues, and the
hashref that results doesn't have any arrayrefs where it should have
single values.
> fix links on release pages not using /pod/$module

- root/inc/breadcrumbs.html
It is possible for a module to be listed as latest, while the dist it is
in is not.  While this indicates a bug in the indexing process, we
should still be presenting working links.
> use version specific release links for non-latest releases

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Release.pm
- root/pod.html
On the release page, link a split pod/pm file as a single module entry, rather than an entry in provides and an entry in documentation.
Also adds a pod source link to the pod page for cases like this.
> link split pod/pm files as single entry

- lib/MetaCPAN/Web/Controller/Pod.pm
<a> elements with id attributes are useful for creating link targets.
> allow id attributes on a elements

- root/account/identities.html
- root/account/turing.html
- root/inc/pager.html
- root/inc/recent-bar.html
- root/inc/twitter/author.html
- root/inc/twitter/module.html
- root/inc/twitter/release.html
- root/wrapper.html
Template::Alloy silently ignores filters applied to objects, including
those with "" overloads like URI.  This means that the AUTO_FILTER html
filter won't be applied, and can open up XSS attacks.  Where we use URI
objects in our templates, use .as_string on them so they will be
properly processed as text and have filters applied.
> always use as_string on URI objects in templates

- lib/MetaCPAN/Web/Controller/Search.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
NOTE! I want people to pay careful attention to this change, try it, try to break it. Search is one of the most important parts of the site and as such I'm cautious.
Hopefully, if I've done my job correctly the results should be exactly the same as currently. I have not exposed the boosts etc.
> Web search uses api endpoint

- lib/MetaCPAN/Web/Controller/Account.pm
The default value for the extra field is the empty string, because it's an empty text box. But it's supposed to be JSON and it was always decoded from JSON, which produced an exception.
> don't un-json `extra` if it's the empty string

- root/account/profile.html
- root/static/less/account.less
This fixes #1847. It was mostly related to the default behavior of some browsers. Possibly that's why it might not have shown up for everyone.
> pressing enter in /account/profile

- root/inc/twitter/release.html
There is a great twitter bot https://twitter.com/cpan_new (here is a source code for this bot https://github.com/punytan/cpan_new )
The `cpan_new` bot uses metacpan api to find out new releases and creates tweets with the links to that releases on metacpan.
But now its tweets are a bit ugly:
This change added author image to the twitter snippet for the release page.
Several examples:
This release page https://metacpan.org/release/ABELTJE/fixedtime-0.05_01 will get:
```
<meta name="twitter:image" content="https://secure.gravatar.com/avatar/8f05c96f651946263df3a55332b80e64?s=130&amp;d=identicon" />
```
This release page https://metacpan.org/release/ATHREEF/Glib-FindMinVersion-0.003 will get such header:
```
<meta name="twitter:image" …
```
> Pretty sharing release page on twitter

- lib/MetaCPAN/Web/Controller/Account/Favorite.pm
Logging in as a user that didn't have a PAUSE account connected was
working, but the code to fetch the favorites list (which controls the
login menu) wasn't interpreting that correctly.  The favorites code was
checking for a "profile", which only exists for PAUSE users.
Instead, use the normal authentication routines and the resulting user
object.
Fixes #1819
> fix login for non-pause users

- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- t/controller/shared/release-info.t
> releaseinfo bug fix

- lib/MetaCPAN/Web/Controller/Pod.pm
Now style attributes for `<img>` tags are not allowed (cf #1844).
Then `<img>` can be bigger than the parent element.
See, for example, https://metacpan.org/pod/release/SKAJI/Parallel-Pipes-0.002/lib/Parallel/Pipes.pm
This pull request adds class "img-responsive" to `<img>` tag in pod so that images are made responsive-friendly.
See also http://getbootstrap.com/css/#images
> add class "img-responsive" to <img> tag in pod

- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
This is a rebased version of https://github.com/CPAN-API/metacpan-web/pull/1609
> No backpans

- lib/MetaCPAN/Web/Controller/Activity.pm
- lib/MetaCPAN/Web/Controller/Mirrors.pm
- lib/MetaCPAN/Web/Model/API/Author.pm
- lib/MetaCPAN/Web/Model/API/Favorite.pm
- lib/MetaCPAN/Web/Model/API/File.pm
- lib/MetaCPAN/Web/Model/API/Lab.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/API/Rating.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
We have leftover query elements that are deprecated since ES 2.0
I hope this change won't cause issues... at least it doesn't break any test.
Of course, later on all these queries will move to the API... this is an interim cleanup/simplification phase.
> convert deprecated query elements

- root/home.html
This should eventually be moved to the footer on the front page, but we currently have no prior art for this, so I'll include it with the top level sponsor ads for the time being.
> Add dealslands.co.uk to front page.

- lib/MetaCPAN/Web/Controller/Account/Favorite.pm
- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/Controller/Favorite.pm
- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Model/API/Author.pm
- lib/MetaCPAN/Web/Model/API/Favorite.pm
with this change WEB will make use of the new `/favorite/by_user` and `/author/by_user` API endpoints instead of sending the Elasticsearch query over.
> use new endpoints by_user

- lib/MetaCPAN/Web/Controller/Author.pm
- root/author.html
Some old logic that was moved out of the templates before, but
doesn't seem to add any value.
The 'latest' value isn't used and the 'aggregated' doesn't
seem right - using existing 'releases' value do the job
just fine.
> Remove redundant code

- lib/MetaCPAN/Web/Controller/Activity.pm
API now provides a new endpoint for activity info, we don't
need to send a query from WEB anymore.
> Replace activity query with new API endpoint

- lib/MetaCPAN/Web/Controller/Favorite.pm
- lib/MetaCPAN/Web/Model/API/Favorite.pm
Make use of the new /favorite/recent API endpoint, replacing
the Elasticsearch query in WEB.
This change also moves the author matching code away from the controller, into the document module.
Note: this PR in API needs to be merged first: https://github.com/metacpan/metacpan-api/pull/675
> Replace favorite recent query with endpoint call

- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Release.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
- lib/MetaCPAN/Web/Role/ReleaseInfo.pm
- t/controller/shared/release-info.t
- t/model/release.t
Replace the Elasticsearch query sending with a call to the new
API endpoit.
This change also fixes the related tests and simplifies the
way 'verisons' query was called.
> Use new /release/versions/DIST API endpoint

- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Release.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
- lib/MetaCPAN/Web/Role/ReleaseInfo.pm
- t/controller/shared/release-info.t
- t/model/release.t
This reverts commit e6151d0293b89060b3b0ed0e72cbac34a6a725ec.
This commit is causing some tests to fail on 'master', will
investigate.
> Revert "Use new /release/versions/DIST API endpoint"

- .tidyallrc
- .travis.yml
- app.psgi
- cpanfile
- cpanfile.snapshot
The changes involving Test::Vars can be removed once we've upgraded to perl 5.26.0  See
https://github.com/houseabsolute/p5-Test-Vars/issues/33
> Fix Travis builds

- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/Controller/Source.pm
- lib/MetaCPAN/Web/Model/API/Favorite.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
While moving queries to API calls some of these ES output
formatters are not needed anymore (and will soon be removed
altogether)
> Remove needless imports

- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
1. /requires/distribution
Removed the query currently being sent to
/search/reverse_dependencies and switched dist rev. deps to use
new API endpoint.
2. /requires/module
Use the new API endpoint instead of the current one.
> Use new /reverse_dependencies API endpoints

- lib/MetaCPAN/Web/Controller/Recent.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
> Use new /release/recent API endpoint

- root/search.html
After moving to a new API endpoint the structure name has
changed from 'results' to 'authors'.
This will fix the authors matches not showing on the search results page.
> Search: fix author search results reading

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Release.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
replace query sending with using new API endpoints.
> use new release endpoints

- lib/MetaCPAN/Web/Controller/Release.pm
- root/preprocess.html
- root/release.html
Move all file sorting into one routine.  Only link one one of a matching
pod/pm pair.  Allow for other interesting files that aren't in the root
directory.
> refactor and improve file sorting on release page

- lib/MetaCPAN/Web/Model/API/Favorite.pm
> send /author/by_user API requests as POST

- root/search.html
this is a quick fix to make the search page work with the reworked inc/favorite.html data (release instead of module).
@haarg I didn't change the included template itself here (it's just a quick fix), but I wanted to save the need to send `favorites = release.favorites` when release is already sent to the template... thought that might break something you did.
anyway - that can be optimized to clean the code a little bit.
> fix call to inc/favorite.html

- lib/MetaCPAN/Web/Controller/Module.pm
- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Release.pm
- lib/MetaCPAN/Web/Controller/Search.pm
- t/controller/pod.t
- t/controller/search.t
Cleans up redirects to use uri_for rather than manual joins.  This will properly re-encode the parameters.
Fixes #1953
> clean up redirects

- lib/MetaCPAN/Web/Controller/Source.pm
alienfile is a recipe used by Aliens during the build process. alienfile, like cpanfile is essentially Perl source.  It is already in use by a few Alien developers aside from myself.  It would be helpful, and I think not harmful to get the same syntax highlighting as cpanfile.
> Add Perl syntax highlighting to alienfile

- lib/MetaCPAN/Web/ActionRole/Sortable.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
goes together with https://github.com/metacpan/metacpan-api/pull/751
> Fix 'sort' param sending in URL for reverse_dependencies

- root/inc/release-tools.html
note that grep.metacpan is only going to perform
the search for the last available version of
the distribution.
> Use grep metacpan for distro search

- app.psgi
Use X-Forwarded-For etc headers to override standard headers.  Existing
Plack middleware don't quite cover the use case we have.  ReverseProxy
will only take the nearest link from X-Forwarded-For, which for us will
be the Fastly servers.  Fastly is configured to override any incoming
X-Forwarded-For header, so we can safely use the farthest link, which
will be the end user.
Other middleware don't support the other headers we would like to use.
> use forwarded headers

- lib/MetaCPAN/Middleware/Static.pm
- lib/Plack/Middleware/Assets/Core.pm
- lib/Plack/Middleware/Assets/Dev.pm
- lib/Plack/Middleware/Assets/FileCached.pm
This changes the processing of the less files to happen on the server in dev mode.  There is no caching or watching because processing the files is generally fast enough, and certainly faster than serving them all into the browser and having them processed there.
This also provides an easier transition away from less (to scss) which I would like to do soon.
> process less files in server when possible

- root/author.html
See https://github.com/metacpan/metacpan-web/issues/1975 :
<<<<
Seems like the result count is now completely missing on authors pages
such as https://metacpan.org/author/BOOK which renders this issue report
outdated - #1507 . I personally really liked the distributions count and
think it should be restored and may likely work on that. What is the
consensus for that? Also note the demise of perlresume -
vti/perlresume.org#15 .
>>>>
> Tentative and untested fix for missing count.

- lib/MetaCPAN/Web/Controller/River.pm
- root/inc/breadcrumbs.html
- root/inc/release-table.html
- root/inc/river-gauge.html
- root/river/gauge.svg
- root/static/js/cpan.js
- root/static/less/global.less
- root/static/less/search.less
- root/static/less/table.less
Layout and some other cleanups for river gauge.  It also embeds the svg directly on pod and release pages.  We could also embed it on other pages if that was desired, but the data wasn't immediately available so I didn't both at this point.
The html br tags in the SVG don't work in Firefox, but an encoded newline seems to, so I replaced them.
Chrome before:
After:
Firefox before:
After:
Chrome before:
After:
Firefox before:
After:
Chrome before:
After:
Firefox before:
After:
> Clean up river gauge

- root/preprocess.html
https://gratipay.news/the-end-cbfba8f50981
> Gratipay (née Gittip) was shut down at the end of 2017

- lib/MetaCPAN/Web/Test.pm
- lib/MetaCPAN/Web/Test/HTML5/Element/SVG.pm
- lib/MetaCPAN/Web/Test/HTML5/TreeBuilder.pm
- root/inc/breadcrumbs.html
- root/inc/river-gauge.html
- root/river/gauge.svg
The river gauge data will often be available on the page including it, so it makes more sense to embed it rather than having a separate request.  This can be extended to other areas later.
This requires adding a hacked-up HTML5 parser to properly handle the SVG elements in the tests.
> Embed river gauge

- lib/MetaCPAN/Web/Model/API/Release.pm
requires https://github.com/metacpan/metacpan-api/pull/731 (so expects tests to fail now)
after this one is merged - remove api.release.by_author_and_name endpoint
> Release: use 'get' endpoint in API

- root/pod.html
Oddly enough, we don't currently have an easy-to-select distribution
name in the POD page (which I need quite often).
> Added distribution name to POD page

- lib/MetaCPAN/Web/Controller/Permission.pm
- root/inc/permission.html
- root/permission/distribution.html
Currently to figure out who can upload a new release of a distribution that will actually get indexed properly, you have to intersect the sets of the owner and co-maintainers of each module in your head. This is a job for a computer.
This PR makes the computer do it.
> Display who can actually release a distribution

- lib/MetaCPAN/Web/Controller/ContributingDoc.pm
- root/inc/release-info.html
This implements a link to a release's `CONTRIBUTING` or similar files in its MetaCPAN page:
Currently this will link to a new route `/contributing-to/$author/$release` which calls ~a new API implemented in https://github.com/metacpan/metacpan-api/pull/802~ `API::Release->interesting_files` and filters for Contributing/Hacking files, as implemented in https://github.com/metacpan/metacpan-api/pull/803.  If a Contributing file is found, it will use the appropriate renderer for it (e.g. HTML if it is in pod, source if otherwise.) If no file is found, it will show a 404 with a suggestion to contact the author.
Fixes #1779.
> Add "How to Contribute" link and functionality

- lib/MetaCPAN/Web/Controller/ContributingDoc.pm
- root/inc/release-info.html
Also adds and uses a dist-specific URL, in addition to the previously existing release-specific URL.
> view contributing files directly rather than redirecting

- root/static/less/global.less
- root/static/less/nav-list.less
If the font size is not what we expect for some reason, it's better to
have the line-height be relative to the font size rather than being hard
coded.
Fixes #2025.
> convert most content uses of line-height to be relative

- root/static/js/cpan.js
- root/static/less/global.less
- root/static/less/table.less
The previous algorithm needed to do many tests of the size of an element
as it attempted to shrink it.  Rather than try to abbreviate from the
exact middle of a string, pick a point part way through and allow the
browser to abbreviate the first half.
> alternate approach to abbreviating table entries

- root/static/js/syntaxhighlighter.js
Rather than changing the location hash to #L{line}, just leave it with
the package target.
If the package is the first line, erase the location hash using
replaceState, avoiding an extra browser history entry, as well as
removing the extraneous empty hash.
Fixes #1980.
> avoid renavigating when getting a #P{package} link target

- lib/MetaCPAN/Web/Controller/Search.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- root/search.html
The search/web/v2 API has a different form.  Rather than each result
being an arrayref, the result is an object with hits containing the top
sub-results.  The total number of sub-results is then available on the
result object.  This gives a more accurate number of sub-results,
without having to return every hit and then throwing away most of them.
> use search/web/v2 api

- lib/MetaCPAN/Web/Controller/ContributingDoc.pm
- root/contributing_not_found.html
- t/controller/contributing-to.t
This adds a new template that renders a standard message for both module
authors and users about adding a Contributing file, as well as
suggestions for its content, to further encourage everyone to contribute
to the CPAN :)
Fixes #2111.
> Better landing for dists missing Contributing file

- cpanfile.snapshot
This module is required by File::HomeDir but only when installed on a
Mac. It's an optional prerequisite. Having the definition in the
cpanfile.snapshot allows carton install --deployment to install
Mac::SystemDirectory if required, and has no impact if it is not.
> Add definition for Mac::SystemDirectory

- root/home.html
The goal is to promote the Perl Conference,
first in US to replace it for YAPC::EU
on June the 22nd. Before going back to normal
after August 15th.
I will set reminder to update this banner over time.
> Add TPC::NA advertising on the HomePage

- root/pod.html
- t/controller/raw.t
When on a latest page using a non-version specific URL, make the source
links use non-versioned forms.
Fixes #1109
> use non-version specific source links on latest pages

- app.psgi
- metacpan_web.conf
Several times, the cached templates on the server have become broken,
resulting in empty pages being output.  To make this easier to resolve,
clear the cached templates on server startup.  Also, since pre-cache all
of the templates at startup time.  This should prevent possible race
conditions of multiple forks trying to cache templates at the same time.
The STAT_TTL will be increased elsewhere, which should mean that the
templates are always cached in memory at server start, and never updated
after that.
> clear and re-cache templates on server start in production

- root/lab/dashboard.html
On the [dashboard](https://metacpan.org/lab/dashboard), there's a link to neil bowers writeup on how to write a good abstract. The link is dead because blogs.perl.org doesn't seem to like https.
Should be replaced by
http://blogs.perl.org/users/neilb/2014/07/give-your-modules-a-good-abstract.html
> s/https/http/ on dashboard blogs.perl.org link

- root/inc/dependencies.html
Possible implementation of #2174. I am not sure on a couple things so please suggest fixes if needed.
* The distribution name needs to be URI-escaped as you can see on https://metacpan.org/release/Text-Tabs+Wrap. I assume the standard Template::Toolkit uri filter can be used. It probably also should be HTML escaped but I don't know a good test case for that.
* I don't really understand the `<i>` tag part, so I just copied it from the disabled stratopan link. I assume this is for the icon next to the link.
* I don't see a benefit to embedding the graph like the stratopan graphs, over just using a standard link that people can open in a new tab if they want to - the same as the other links that are there.
> Link to dependency graphs

- root/inc/dependencies.html
The dependency graph may be configured to show dependencies from other phases or relationships, so it may be useful even if the runtime requirements are empty.
> Link to dependency graph unconditionally

- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Model/API/Changes.pm
Context: https://github.com/metacpan/metacpan-web/issues/2142
With this PR, the output of `/feed/recent` action now contains the latest change log entries for each releases. Here's how it looks like when rendered with [Vienna RSS reader](https://www.vienna-rss.com/)
In order to make it looks nice, the "summary" field of each entry is changed to be HTML. This might break some feed consumers. Should it be preferred, I can make this effective only when a parameter is given.
With the current implemention, when there are N recent releases to render (N is usually 100), metacpan-api is queried N/10 times instead of 1 times. I tried with 1 very long query but metacpan-api wouldn't return N results. 10 seems to be the upper bound. I'm guessig this is due to the default resultset size of …
> Latest changelog in feed

- News.md
- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Source.pm
- lib/MetaCPAN/Web/Model/API/Changes.pm
- lib/MetaCPAN/Web/RenderUtil.pm
- lib/MetaCPAN/Web/View/HTML.pm
- root/source.html
- t/controller/source.t
Relating to #2191, this PR seeks to render .md files as HTML instead of raw source. Comments, questions and suggestions welcome. I'm new to Catalyst, so one of the things I'd like to address is the code duplication between `source.html` and `md.html`.
> Render Markdown source files as HTML

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- root/inc/notification.html
- root/pod.html
- root/release.html
- root/static/less/notification.less
- root/static/less/style.less
- t/model/release-info.t
Highlight modules or dists with ADOPTME or HANDOFF or NEEDHELP.
A notification will display at the top of the page in /release and /pod if ADOPTME, HANDOFF or NEEDHELP is found as an author within the modules permissions.
> Highlight modules/dists that have a special co-maintainer (ADOPTME, HANDOFF or NEEDHELP) - Closes #1643 - Attempt 2

- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- t/model/release-info.t
The logic was only looking up in the co_maintainers for an author that was NEEDHELP|ADOPTME|HANDOFF. Now it will first check the owner and then the co_maintainers.
Closes #2234
> Display notification when owner is a special PAUSE author.

- root/author.html
- root/favorite/recent.html
- root/home.html
- root/news.html
- root/pod.html
- root/recent.html
- root/release.html
- root/source.html
- root/wrapper.html
Various readers and browser add-ons show the link title in feed
discovery phase, and the title may also end up as the title of a
subscription in a feed reader. A plain "RSS" doesn't look good in
either, and is ambiguous in subscription lists.
> Sync RSS link titles with respective feeds

- root/inc/notification.html
The API returns inconsistently either an array or a string for author.email take the following examples:
http://localhost:5000/v1/author/NEILB is indexed as "email" : "neil@bowers.com" (locally)
https://fastapi.metacpan.org/v1/author/NEILB is indexed as "email" : ["neil@bowers.com"]
https://fastapi.metacpan.org/v1/author/REHSACK is  "email" : "rehsack@cpan.org"
So update the template logic to check first if an array email.0
Also first check for asciiname before name, which should prevent breakage in the mailto 'URI' for cases like:
"asciiname" : "Audrey Tang"
"name" : "☻ 唐鳳 ☺"
I don't think any validation exits on the asciiname field to validate it is actually ascii, perhaps this needs to be added as a seperate ticket.
Closes #2237
> mailto link: Email address is ARRAY(...)

- .travis.yml
- git/hooks/pre-commit
Enabling TidyAll stashing leads to files being deleted when the hook runs.
> Fix pre-commit hook

- app.psgi
When run from a docker container the
local var directory is read only, we
should not use it when run from docker.
> Use /var/tmp for tmpdir in docker

- root/home.html
Display two by default, then show all of them
on demand.
By default only show two events
then on click list all remaining events
note: now using `The Perl and Raku` for both events, the screenshot is not up to date
> List 2020 coming Perl Events

- Dockerfile
relying on nodejs=10.17.0-1nodesource1 breaks building Dockerfile because it's not found.
https://github.com/metacpan/metacpan-docker/issues/67
> fixes metacpan-docker/issues/67

- root/home.html
The workshop was cancel, promote other events.
> Remove DC-Baltimore Perlyglot Workshop 2020

- .mailmap
- README.md
- cpanfile
I am not using Docker, and the instructions didn't cover setting up the JS side.  This PR adds installation of JS packages to the README.
I'm using my work computer at the moment (with permission), so I'm adding myself to the `.mailmap` also.
> Expand non-Docker hacking instructions

- root/source.html
- t/controller/source.t
This provides one-click access from a latest-release source view (e.g., `/release/Moose/source/lib/Moose.pm`) to a versioned source view (e.g., `/source/ETHER/Moose-2.2012/lib/Moose.pm`).
Fixes #2260.
Ping @dboehmer
> Add permalink to source views

- root/inc/release-tools.html
- root/pod.html
Display "Development release" to side bar (under "Module version")
with matching text color to the release text in bread brumbs area
for dev ("maturity": "developer") releases. This is to make it
more clear that a release (especially when the version only has
an underscore, and no "TRIAL" or other such clues) is in fact a
development release.
When there is only one version for a distribution, display a
disabled drop down with "No other versions" text in place of,
and matching the style of, the "Jump to version" drop down, in
the side bar.
Hide "Latest version" link in side bar when there are no stable
("maturity": "released") releases, which would result in a 404
if followed.
> Side bar changes for better clarity and presentation

- README.md
- cpanfile
- cpanfile.snapshot
- t/controller/search.t
The CI has been failing since April or so. Partly that's due to a dep not being there (which this fixes), partly because the search has improved and putting `">` on the end of a search string doesn't fail now.
The rest is because the MetaCPAN backend API no longer returns results from https://fastapi.metacpan.org/author/search?q=author:rjbs%20app&from=0, which the -web tests depend on. I am looking at fixing that.
> CI tests partial fix

- README.md
This would be outside of my scope, but do you think making the CI report failures on `master` (only, and only on first break and then fix) on `#metacpan` would be a good idea?
> Add git hook and tidyall stuff to README

- root/static/less/nav-list.less
- root/static/less/responsive.less
This fixes the empty space at the top of the left sidebar on desktop by
only applying it on smaller viewport sizes. Also, move it to the correct
class, which fixes the margin not appearing on the about page.
> fix empty space on sidebar on desktop

- app.psgi
Partly address #2311 by adding a CSP.
It doesn't restrict images, and only restricts JavaScript so as to mitigate the risk of XSS via MetaCPAN, since we use SSO.
> Add a Content-Security-Policy allowing JS only from GA and us

- root/home.html
I'm not sure we have any other event to advertise for now, let's remove the Conference in the Cloud banner.
> Remove Conference in the Cloud banner

- app.psgi
- root/about/contributors.html
- root/static/js/github.js
This uses AJAX instead of JSONP for interacting with GitHub API. Lessons learned:
- jQuery uses JSONP if there is a `callback=?` CGI arg on its URL
- with JSONP, it calls `success` with an object with keys `meta` and `data`
- with proper AJAX, the `success` receives the `data` directly, but its third arg is a `jqXHR` which you can call `getResponseHeader` to achieve the same thing as the `meta` information
The CSP is amended back to not needing GitHub as a source of scripts.
> Zap JSONP from GitHub API use

- lib/MetaCPAN/Web/Model/API.pm
- t/controller/feed.t
This should make both the tests and the website itself more reliable.
> Retry once if API call fails

- lib/MetaCPAN/Web/Controller/ContributingDoc.pm
- lib/MetaCPAN/Web/View/HTML.pm
https://metacpan.org/pod/YATT::Lite::XHF blows up as it has a runtime Perl requirement of: `>= v5.10.1, != 5.17, != v5.19.3`. This fixes that.
> Make tolerant of diverse Perl version-spec

- lib/MetaCPAN/Web/Model/API/Permission.pm
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- root/inc/notification.html
- t/model/permission.t
- t/model/release-info.t
~~This suppresses `writev` warnings on `EPIPE`.~~ But mainly it addresses, and therefore hopefully fix #2268 and fix #2293. @karenetheridge Do you agree?
EDIT: remove the `writev` stuff in favour of #2346
> Expand the "notification" addressee list for ADOPTME etc

- lib/MetaCPAN/Web/Controller/Account.pm
- lib/MetaCPAN/Web/Controller/Account/Favorite.pm
- lib/MetaCPAN/Web/Controller/Search/AutoComplete.pm
- lib/MetaCPAN/Web/Controller/SysAdmin/DataCenters.pm
- lib/MetaCPAN/Web/View/JSON.pm
- root/static/js/cpan.js
- t/controller/search/autocomplete.t
- t/lib/MetaCPAN/Web/Controller/Test.pm
The account/favorite/list_as_json end point throws a forbidden error if
you aren't logged in.  While this works, it results in errors in the
browser console.  Add a new end point that returns a false value we can
check instead of an error.
> add new endpoint to check being logged in that doesn't error

- root/release.html
- root/static/less/release.less
This resurrects (with a little updating, it was over 3000 commits old) @plu's issue-224 branch. The same tabular change is also now applied to the documentation and provides sections.
> Tabular display on /release page

- root/inc/dependencies.html
Now that @Grinnz's excellent cpan-deps-graph can support showing deps for non-latest versions, this changes the link to that service to add the `dist_version` if viewing the non-latest version.
> If not latest release, link to that version of cpan-deps-graph

- .hadolint.yaml
- Dockerfile
This makes it easier to test things in a Docker container as we won't always need to build one first. It also makes for less differences between the deployed environment and the test environment. If we ever need to slim down the containers, we can worry about that later.
> Default to installing test deps in Docker images

- root/home.html
Using metacpan on mobile, my phone likes to drive me nuts by auto-correcting my
search terms, uppercasing stuff and finally putting red squiggles under the
search term. I usually search for package names and unfortunately their names
often aren't in my phone's dictionary. Those three attributes should keep all
mobile browsers from meddling with search terms.
> Add attributes to search input to disable autocorrect, autocapitalize, and spellcheck

- lib/MetaCPAN/Web/RenderUtil.pm
@davorg added the rowspan/colspan attributes for td here: da7060439dd145390cb92d1bc7ce62d8fd6e41a5. However, he omitted to add them for th. See this comment: https://github.com/metacpan/metacpan-web/commit/da7060439dd145390cb92d1bc7ce62d8fd6e41a5#commitcomment-45804935
> In HTML, allow <th> the same attributes as <td>

- root/home.html
[As requested](https://github.com/metacpan/metacpan-web/pull/2422), a fix for the commit yesterday. Each alert is now an individual row, and renders as requested on mobile and large screens. Screenshots attached.
> home.html - render alerts as rows

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Model/API/Permission.pm
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- root/inc/notification.html
- root/static/less/notification.less
Using similar visual indicators to what we have in place already for ADOPTME, NEEDHELP, and HANDOFF, provide an indication that a Module has been Deprecated, or possibly the entire Release/Distribution.
Relates to metacpan/metacpan-web#1435
> Show notifications for Deprecated modules/distributions

- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
While this worked great in Dev on a partial index, something fishy is going on and the notification is showing incorrectly in Production.
Until we can diagnose the cause and correct, disable the display of Deprecated notifications.
Related to #2438
> Disable "deprecated" notifications

- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
This reverts commit 19df9e5be15a14ef4f8fa44d15eca7c9d8046ae2.
Re-enables "Deprecated" notifications.
As per discussion in metacpan/metacpan-web#2438, the data in ElasticSearch has been updated and now returns proper boolean values (instead of potential string `"true"` or `"false"`).
With the data corrected, we should now be able to re-enable these notifications for deprecated Modules/Distributions.
> Re-enable "deprecated" notifications

- root/browse.html
- root/favorite/leaderboard.html
- root/inc/release-table.html
- root/static/js/cpan.js
- root/static/less/table.less
This attempts to improve the layout of the release table by fixing the width of the date column, giving more space to release names on wide screens, and trying to cut release names in half for abbreviation on word boundaries where possible.
> Improve release table layout

- app.psgi
- root/author.html
Remove the PayPal tracking pixel.
Remove the Flattr button. The script for it no longer exists, and they seem to be using a different model now.
> Clean up some donation options on author pages

- root/static/less/style.less
DejaVu Sans Mono is not the best looking font, and also has some issues:
https://gitlab.gnome.org/GNOME/pango/-/issues/392
Replace it with Liberation Mono, which is also included on many debian
systems. Also re-order the fonts to prefer Consolas on most Windows
systems.
> update monospace fonts

- .perlcriticrc
- tidyall.ini
Rather than relying on the theme and severity which are unpredictable,
explicitly list the perl critic policies we want to use.
Also remove all the excluded files from the critic/tidy checks, since
they are all passing now.
> be explicit about perl critic policies

- lib/MetaCPAN/Web/Model/API/Release.pm
- root/inc/breadcrumbs.html
- root/inc/release-info.html
Rather than getting specifically the version from CPAN::DistnameInfo in
one case, provide it for all release data. This is then used to simplify
part of the template that was re-calculating the version from the dist
name.
> always provide distnameinfo with release data, and use it in templates

- root/inc/release-info.html
- root/inc/release-tools.html
- root/release.html
If x_help_wanted was specifed, it would appear once on the sidebar on
pod pages, but twice on release pages.
Move the help wanted message to be consistently shown above the IRC
banner or activity graph, and not shown twice.
> consistently show help wanted once on sidebar

- root/inc/release-tools.html
The size is presented in bytes, not bits
> Fix display of release download size

- root/inc/dependencies.html
CPANdeps will go away soon, so removing the link. Metacpan has its own forward and reverse deps these days so it's not really needed.
> CPANdeps will shortly go away so stop linking to it

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Web/Test.pm
- t/controller/changes.t
We were only using CSS selectors for one test, which can trivially be
switched to xpath. This makes the tests more consistent, removes an odd
interface, and removes a prereq.
> use xpath for all tests

- .github/workflows/codeql-analysis.yml
The checks will fail due to only having read-only access, but they will
still get checked by the pull request event.
> skip codeql on dependabot push

- cpanfile
- cpanfile.snapshot
Add some additional transitive deps to the cpanfile and snapshot to
cover a wider range of perl versions. The system that is automatically
updating the snapshot is running a different perl version than the
current live servers, so it won't have the same modules available. We
need to ensure all of the potentially required modules are listed in the
snapshot or the production machines won't install them.
Also document this a bit better in the cpanfile by splitting out these
deps to its own section.
> include more transitive deps in cpanfile

- .github/workflows/update-snapshot.yml
- cpanfile
- cpanfile.forced
The cpanfile.snapshot file is generated using a version of perl that may
not match what we are deploying on. Additionally, some dependencies may
not predictably be installed with a normal cpm/carton run. Both of these
cases can end up with modules missing from the snapshot which are
required when installing on various systems.
We could try to provide cpm with the deployment perl version, but that
means it may not be appropriate for other perl versions.
Instead, we provide a list of modules that should always be installed,
even if they are provided by core. We use cpanm to extract these prereqs
from a secondary cpanfile, then pass them to cpm to install. cpm can't
use the alternate cpanfile directly, because it only pays attention to
the --reinstall flag when provided a module list. cpanm …
> force install all transitive modules when building snapshot

- .perltidyrc
- lib/MetaCPAN/Web/Controller/Account/Favorite.pm
- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Root.pm
- lib/MetaCPAN/Web/Controller/Search/AutoComplete.pm
- lib/MetaCPAN/Web/Controller/SysAdmin/DataCenters.pm
- lib/MetaCPAN/Web/Test.pm
- root/about/about.tx
- root/about/faq.tx
- root/pod.tx
- t/encoding.t
Expand perl tidy options to be more readable.
Return JSON from JSON end points even on errors.
Per-page classes should be part of the templates, not the controllers.
Improve a few links on the about page.
Silence a warning in the encoding test.
> Several minor cleanups

- t/controller/pod.t
This test should always pass, and always seems to. This generates noise
about a passing TODO test. The logs of it failing are no longer
available, making debugging difficult.
The restored check will either continue to work, or will help reveal the
failure and allow a proper fix.
This reverts commit 8821b4a8f0be06ffd332be68d48cf0c4e9e38be5.
> Revert "Mark flaky Moose Pod content comparison test as TODO"

- root/static/less/pod.less
- root/static/less/syntaxhighlighter.less
The problem is that `.pod pre` and `.syntaxhighlighter` both apply `overflow` in some way. By turning off `overflow-x` on `.syntaxhighlighter`, we end up with the outer `.pod pre` scroll area, which is larger, since that is the one that applies `padding`. This makes it easier to scroll horizontally on one-line code blocks on mobile.
I noticed this on https://metacpan.org/dist/App-perlimports/view/script/perlimports, it has a lot of examples in the SYNOPSIS that are hard for me with my fat fingers to scroll on my mobile.
> Make scrollable area larger for pod pre areas

- root/about/contributors.tx
- root/account/profile.tx
- root/author.tx
- root/base.tx
- root/base/release.tx
- root/home.tx
- root/inc/contributors.tx
- root/inc/favorite_table.tx
- root/inc/module_install.tx
- root/inc/notification/base.tx
- root/no_result.tx
- root/recent.tx
- root/release.tx
- root/source.tx
- root/static/css/jquery.autocomplete.css
- root/static/js/cpan.js
- root/static/less/author.less
- root/static/less/global.less
- root/static/less/home.less
- root/static/less/lab.less
- root/static/less/notification.less
- root/static/less/print.less
- root/static/less/release.less
- root/static/less/responsive.less
- t/controller/author.t
- t/controller/changes.t
Prefixed all non-POD related ids with metacpan_
Also left out #index* ids since those also come from pod2html according to discussion in the #metacpan channel on irc.perl.org
This is to address issue #1590
> Prefixed all non-POD related ids with metacpan_

- root/home.tx
These were to have been removed in April of 2020.
> Remove sponsor logos from last meta::hack

- root/account/identities.tx
- root/account/profile.tx
- root/base/release.tx
- root/browse.tx
- root/inc/notification/base.tx
- root/login/openid.tx
- root/source.tx
- root/static/js/cpan.js
- root/static/less/pod.less
Some icon names have changed over time, or we were using aliases. Update
to the new names so we don't need the shims.
> update to new fontawesome icon names

- root/static/js/cpan.js
- root/static/less/pod.less
- root/static/less/style.less
Most icons on the site are solid icons, but the toggle for the right
aligned index looks significantly better using the regular icon.
Also adjust the CSS to not rely on the fontawesome icon classes.
> improve right aligned index toggle

- lib/MetaCPAN/Web/Controller/Changes.pm
For changes urls under /dist/, it was forwarding to the /view/release
action, which expects the author and release in the stash. Instead,
forward to /view/dist, which works with the distribution name.
> fix /dist/$dist/changes urls

- root/base/release.tx
Some further clarification of the purpose of this metric. Not sure if it's too much to put in the tooltip. Alternatively maybe the bus factor could link to a FAQ section with an explanation of it and the river stage.
> Bus factor tooltip - further explanation of purpose

- root/base/release.tx
- root/browse.tx
- root/inc/release_status.tx
- root/source.tx
- root/static/less/global.less
Rather than needing specific classes for different pages, use the
surrounding tags to adjust the padding. Move the related css out of the
breadcrumb related classes, since they have essentially nothing in
common. Also eliminates a use of .extend(), which is a potentially
confusing less feature which we should move away from.
> update CSS used for release maturity banner to avoid page specific classes

- root/home.tx
This is adding a small text banner to the HomePage for TPRC 2022 https://perlconference.us/tprc-2022-hou/
attached is a snapshot of the rendering 
Thanks for your consideration
> Advertise TPRC 2022 on HomePage

- root/static/js/github.js
GitHub no longer allows use of the git protocol. Remove it from the
popup for GitHub repositories.
> remove git clone URL from github popup

- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- root/base/release.tx
- t/controller/shared/release-info.t
Authors will use various forms of URLs when including repository
metadata. For known git hosts (only GitHub so far) we can clean up those
URLs to be presented better in the UI.
One example of this is including just a clone URL using git://. This
isn't friendly to present in the UI to start with, since it doesn't lead
to a web page, but also GitHub no longer supports git:// cloning. There
is also little purpose of presenting a https web link with a second link
for cloning that includes .git at the end. Either one could be used for
cloning.
> clean up GitHub repository URLs

- root/static/js/github.js
Hello, this PR is bit nitpicky but just fixes the word "GitHub" to have the correct case ("Github" -> "GitHub") on the small tooptip window on the left sidebar of metacapan website. 
Here are the screenshots of the change (this example is https://metacpan.org/dist/XML-LibXSLT):
**before**
**after** (tested on my dev environment)
> Fix case of "GitHub"

- .github/workflows/update-snapshot.yml
When updating the cpanfile.snapshot, use the metacpan-bot user to clone
the repo. This means it will also push as metacpan-bot. This will
hopefully prevent the push from being sometimes attributed to whoever
initially created the scheduled action.
> update-snapshot - Checkout and push as metacpan-bot

- package.json
- yarn.lock
Originally, package.json was listed as a dependency, apparently
erroneously. It was later changed to pkg.json when the package was
renamed, ignoring that it was not needed at all.
> remove pkg.json dependency and upgrade deps

- root/pod.tx
> fix 'read the source' link on module pages with no pod

- root/inc/keyboard_shortcuts.tx
Just noticed some missing slash. Does not change the appearance.
> Missing slash in shortcuts table

- root/base.tx
The previous commit were missing some edits to the logo size and
position
> Make geocode logo fit in better with the existing logos

- root/about/sponsors.tx
Hello :smile: 
Keep the sponsor paragraph for Kritika.io but remove links since service is down for about 1 year and at some point it will link to something unrelated.
> Drop links to Kritika.IO

- lib/MetaCPAN/Web/Model/API/Author.pm
- root/author.tx
- root/base/release.tx
- root/inc/author_pic.tx
- root/inc/twitter/author.tx
- root/recent/topuploaders.tx
- root/search.tx
In an author has an "empty" name set, various parts of the UI will not have anything to click on, breaking navigation.
Detect this by checking for word characters in the author name, and falling back to the PAUSE id if there are none. If the API were to provide a display_name, either through a similar check like we are using or as a field that can be filled in, it would be preferred over either the name or the PAUSE id.
> cope with authors with nothing visible in their name

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Web/Controller/Account.pm
- lib/MetaCPAN/Web/RenderUtil.pm
Rather than hard coding a size, or trying to accept it as a parameter, return a template string for the avatar, and let the client format it.
The Gravatar::URL module won't allow a string like this, but the module is doing basically nothing for us, so we can just remove it.
> update Gravatar handling to provide a template string to login_status

- root/author/releases.tx
- root/base.tx
- root/base/search.tx
- root/inc/release_table.tx
- root/login/pause.tx
- root/no_result.tx
- root/search.tx
- root/static/js/cpan.js
- root/static/less/global.less
- root/static/less/home.less
- root/static/less/nav.less
- root/static/less/search.less
- t/controller/search/suggestion.t
- Do not display sidebar and slidepanel icon in header if there is a `no-sidebar` class added to the body tag. As described in https://github.com/metacpan/metacpan-web/issues/2749
- Ensure icons stay in viewport on an actual mobile device (for some reason the nav looks OK in Chrome dev tools, but not when actually viewing on a mobile device)
- ~~Use gravatar for a logged in user icon as described in https://github.com/metacpan/metacpan-web/issues/2757~~ This will be done in a separate PR.
- Stop the shifting of the nav links in the navbar as the page is checking for logged in status: https://github.com/metacpan/metacpan-web/issues/2752
- Round the corner of the button icons and search bar in the navbar
- Add dropdown / chevron icon to the logged in / logged out icons
**Mobile device …
> Add no sidebar class

- root/base.tx
- root/static/js/cpan.js
- root/static/less/nav.less
This shows the gravatar for logged in users that have a PAUSE account linked.
In the future, we could consider extending this to show GitHub avatars for users that don't have a PAUSE account.
> Show user avatar in account button

- root/static/less/global.less
- root/static/less/nav.less
In https://github.com/metacpan/metacpan-web/pull/2767, I introduced a bug where I set `overflow-y: hidden` for the `navbar-right` in order to get the nav icons to show in the viewport on Safari mobile. I was so focused on fixing that, that I didn't realize the dropdown menu won't appear when the logged in / out icon is clicked.
Fixed issue:
> Fix logged in status icon dropdown

- root/static/less/breadcrumbs.less
> Use flex instead of inline

- lib/MetaCPAN/Web/Model/API/Changes/Parser.pm
When parsing the date from a change log, the short month was being matched, and the index of the match was used as the month. Since the index starts at 0, this resulted in the month being off by one.
Add one to the index before using it in our short month to number hash.
Fixes #2780
> fix month in changelog parser calculations

- root/static/less/style.less
This reduces the size of our generated CSS a bit, and also fixes a warning that always shows up in the browser console about using the 'zoom' property.
> remove unused bootstrap less includes

- root/static/less/footer.less
- root/static/less/global.less
- root/static/less/nav.less
When scrolling past the top of the page, the header would move down from the top of the display, and show white behind it. And scrolling past the bottom would also show white.
Change the positioning of the header from sticky to fixed. This means it will always be attached to the top, even with overflow scrolling. sticky is more useful for things further down the page that you want to attach to the top once you've scrolled past them. Changing to fixed also results in the header not taking up any space in the layout. Adjust the top margin of the page content to accomodate for this. This is makes rules match for the desktop and mobile layout.
We can set the background color browsers use for overflow scrolling with the background on the html element. We're already setting the body background …
> improve display when overflow scrolling

- lib/MetaCPAN/Web/Model/API.pm
When connecting with HTTPS, proper hostname verification isn't enabled without setting the verify scheme.
> Enable full TLS hostname verification on API requests

- lib/MetaCPAN/Web/Model/API/Changes.pm
version handles large numbers badly, possibly producing version numbers like v.Inf. These will emit warnings, so we can just make those fatal and avoid the version object conversion.
> Changes Parser: avoid warnings with too large numbers

- lib/MetaCPAN/Web/Controller/Activity.pm
- root/activity.svg.tx
- root/inc/river_gauge.tx
- root/river/gauge.svg.tx
svg XML header and doctype are generally not necessary, and removing them makes it easier to embed the files. Also rename the variable used for activity from the ambiguous 'data' to something else.
> remove unneeded svg headers to make embedding easier

- lib/MetaCPAN/Web/Model/API.pm
Properly enabling hostname verification requires passing both a SSL_verifycn_scheme option as well as a SSL_verifycn_name option. We can take the name from the URL.
This is a replacement for #2801, which didn't work when deployed to the servers.
> enable TLS hostname verification

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Source.pm
- lib/MetaCPAN/Web/Controller/View.pm
- lib/MetaCPAN/Web/Model/API/File.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- lib/MetaCPAN/Web/Role/FileData.pm
- root/base/release.tx
- root/browse.tx
- root/inc/dependencies.tx
- root/inc/link_to_file.tx
- root/inc/module_install.tx
- root/inc/twitter/module.tx
- root/inc/version_select.tx
- root/inc/version_select/diff.tx
- root/pod.tx
- root/raw.tx
- root/release.tx
- root/source.tx
- root/static/less/silk.less
- t/controller/source.t
This adds a role for cleaning up file data coming from the API. Fixes the MIME type, and sets some flags relating to the available modules.
Uses the new more consistent MIME type directly in some places, rather than having matches on the file extension in various places around the codebase.
Also renames a bunch of variables to file rather than module, for better consistency.
> Refactor handling of file data

- lib/MetaCPAN/Web/Model/API/Changes.pm
Some versions will fail to parse. If compared directly to another version with eq, version.pm will try to parse the version again. Since we already tried to parse the version, this isn't useful.
All valid versions will already have been normalized, so we can just compare them as strings.
> Changes Model: compare parsed versions as strings

- root/static/less/pod.less
Pod content with =item followed by text (rather than a number or *) will be represented in HTML as <dt><dd> elements. The <dd> elements should have some indentation to allow for nesting to be represented.
> add indentation for =item with text

- root/static/less/global.less
When the body content is very small, the headings will expand. Limit the first two rows to the size of their content.
Example of page showing bug: https://metacpan.org/release/ABH/Mozilla-CA-20120118/source/lib/Mozilla
> limit headings in content to only needed size

- lib/MetaCPAN/Web/View/JSON.pm
It takes a minimal amount of processing power, and maked debugging easier.
> always output json sorted

- lib/MetaCPAN/Web/Model/API/Changes.pm
If the parsed version is not an object, it failed to parse. In that case, comparing using version's routines isn't going to give a useful result anyway. Use a normal cmp by forcing both args to be strings if one isn't.
> Changes model: try harder to avoid comparing versions to non-versions

- lib/MetaCPAN/Web/Model/API/Changes.pm
- lib/MetaCPAN/Web/Model/API/Changes/Parser.pm
This should actually really this time fix the handling of non-versions that look like versions in changes files.
> Fix handling of non-versions when parsing Changes files (again)

- root/author/releases.tx
- root/base.tx
- root/home.tx
- root/inc/no_sidebar.tx
- root/login/pause.tx
- root/no_result.tx
- root/pod.tx
- root/search.tx
- root/static/js/search.js
- root/static/less/global.less
- root/static/less/home.less
- root/static/less/nav.less
- root/static/less/print.less
- root/static/less/search.less
Create a mixin template that can be used to remove everything connected with the sidebar. This removes the actual content from the pages, making it unnecessary to remove the elements with CSS. A class is still provided to allow changing the grid layout.
Normalize the home page to mostly work like other no sidebar pages. Also have it remove the extra elements it does not want, rather than hiding them. With this cleanup, the separate banner code for the home page is not needed.
Fix the grid row sizing to use max-content. This fixes various places that would show large empty spaces for elements that were missing.
> clean up code for pages with no sidebar, and grid layout

- root/home.tx
Before the redesign this text was added in #2200 to assist with confusion regarding the roles of MetaCPAN and CPAN.
The text should be centered but I don't know the appropriate way to achieve that here.
> Restore description of relationship to CPAN on home page

- lib/MetaCPAN/Middleware/Static.pm
- root/account/turing.tx
- root/static/js/recaptcha.js
This eliminates an inline script, which will help tighten up the CSP rules in the future. Also removes another id.
> move recaptcha initialization to separate javascript file

- lib/MetaCPAN/Web/Model/API/Changes.pm
When finding the changes for a version v1.2.3, where the change log contains "1.2.3", we need to be comparing the versions as version objects rather than strings. But we still need to prevent version.pm from trying to inflate the other version it is being compared to, because that already failed. Force a stringificiation on both versions if either failed to parse.
> changes parser: fix comparing versions that are in different forms

- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Model/API/Changes.pm
The previous code would batch requests in the controller, manually generate URLs in the model, and had odd inputs and outputs.
Rewrite the changes model by_release method to accept a simple list of release paths, handling batching internally, and return a simple hashref. Doing the batching internally makes it easy to add concurrency to the requests.
Also fix the version regex to understand v prefixes.
> rewrite changes handling for rss feed

- lib/MetaCPAN/Web/API/RequestInfo/Orchestrator.pm
- lib/MetaCPAN/Web/Model/ReleaseInfo.pm
- t/controller/release.t
- t/controller/shared/release-info.t
- t/model/release-info.t
A substantial refactoring of ReleaseInfo to allow creating a requesting
object, then later deciding what information to request.
The existing APIs are maintained for now, but in the future users will
be adapted to use the `->via_dist` and `->via_release` methods. The
`full_details` option will go away, with the extra details being attached
by the release controller. This ReleaseInfo object can be placed in the
stash immediately, rather than needing the pass the dist, author, or
release information on.
The Orchestrator object coordinates fetching in two batches, info based
on the dist and info based on the release. The order of these depends on
which information you start with. Additional information can be
requested using the `->with_*` methods before calling fetch.
> refactor ReleaseInfo to specify release first and requested data later

- lib/MetaCPAN/Web/Controller/Source.pm
- lib/MetaCPAN/Web/Model/API.pm
When Text::Xslate is given data with the utf8 flag off, but with valid
non-strict utf8 sequences in it, those sequences will be decoded. That
will then produce errors when attempting to encode it for output. We
only really run into this problem when showing the source of a file,
since those may have arbitrary bytes.
Force the source content given to Xslate to always have the utf8 flag on,
so that Text::Xslate inserts the non-decoded "characters" directly into
the output. They will essentially be mojibake, but this is acceptable
since the original file had badly encoded data in it.
> Fix handling of non-UTF8 source code

- .github/workflows/test.yml
- Dockerfile
- Bump node from version 10 to 18
- Clean yarn cache in Docker build
> Bump nodejs from 10 to 18

- .github/workflows/codeql-analysis.yml
- Bump GH checkout action from v2 to v3 in CodeQL build
- Bump Ubuntu from 20.04 to 22.04 in CodeQL build
- Bump CodeQL actions from v1 to v2
> Bump versions in CodeQL action"

- lib/MetaCPAN/Web/Controller/Author.pm
match call params order with sub:
> sub all_by_author {
>     my ( $self, $pauseid, $page, $page_size ) = @_;
> all_by_author: called with the wrong params order (GH#1126)

- .github/workflows/build-production-container.yml
Previous incantation pushed the latest tag. This incantation will push all the tags, which includes the git sha allowing its use when deploying containers.
> Add push all for docker image push

- .github/workflows/build-production-container.yml
When pushing all tags, you can't specify a tag name. Who knew?
> Remove tag name from docker push

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Web/Controller/Feed.pm
- lib/MetaCPAN/Web/Types.pm
`CPAN.pm` uses `http://search.cpan.org/uploads.rdf` to find recent uploads, which it of course expects to be in RDF (RSS 0.90, 1.0, 1.1) format. This URL is now a redirect to metacpan, which provides the feed in RSS (RSS 0.91, 0.92, 2.0) format.
Re-introduce an RDF format feed to allow fixing compatibility with `CPAN.pm`. Changing the redirect on `search.cpan.org` will be addressed later.
> re-add RDF recent feed for use by CPAN.pm

- root/base.tx
The ‘FAQ’ link in the website footer is relative, meaning that it can go to the wrong place when not on the site homepage. For instance, on <https://metacpan.org/pod/feature> it links to <https://metacpan.org/pod/about/faq>, relative to the `/pod/` path, instead of the correct <https://metacpan.org/about/faq>.
This adds a leading slash, to always link to `/about/faq`.
> Fix footer FAQ link

- root/about/contact.tx
- root/base.tx
Closes https://github.com/metacpan/metacpan-web/issues/2891
Unfortunately, the 'square' icon is not available for Mastodon in fontawesome - not even in the latest version, I checked. Still I think it looks nice.
> Replace refs to @metacpan twitter to mastodon

- root/inc/release_table.tx
We have different types of releases (development, testing, only for cpan) and there were no visible identification of these.
Fixes #2954
> Add colors for release name in recent page

- lib/MetaCPAN/Web/Controller/Pod.pm
- lib/MetaCPAN/Web/Controller/Pod2HTML.pm
- lib/MetaCPAN/Web/Model/API/Author.pm
- lib/MetaCPAN/Web/Model/API/File.pm
- lib/MetaCPAN/Web/Model/API/Module.pm
- lib/MetaCPAN/Web/Model/API/Pod.pm
- lib/MetaCPAN/Web/Model/API/Release.pm
- lib/MetaCPAN/Web/RenderUtil.pm
- lib/MetaCPAN/Web/Role/FileData.pm
- root/pod.tx
- root/pod2html/pod2html.tx
- root/static/js/cpan.js
- root/static/less/pod.less
This separates the table of contents from the rest of the pod in the perl code, allowing it to be handled separately in the template. Includes some refactoring to do more work in the API modules.
Fixes #2972
> split table of contents from pod and style statically

- root/static/less/global.less
The scroll-margin-top CSS property is used with scroll snapping, which we aren't using. It also currently triggers a bug in Chrome: https://issues.chromium.org/issues/41495913
> remove scroll-margin-top as unneeded

- Dockerfile
As described in this blog post:
https://petermalmgren.com/signal-handling-docker/
Add dumb-init as the initial process to control PID 1 and allow for proper signal handling within the container.
> Add dumb-init as entrypoint

- root/robots.txt
The source, raw, and diff URLs have changed. Update robots.txt to cover the new URLs.
> update robots.txt to block new source urls

- cpanfile
- lib/MetaCPAN/Web.pm
- lib/MetaCPAN/Web/Controller/Account/Favorite.pm
- root/static/js/cpan.js
The proper way to check if a request should return JSON is using the Accepts header. And since we're making these requests in JS, we can control that.
The browser detection in the ForBrowsers plugin is based on a IE7 world.
> use accepts header, not ancient browser detection

- root/static/less/global.less
Despite the documentation, it does have an impact. Chrome seems to be fixed now.
> bring back scoll-margin-top

- root/base/release.tx
I actually noticed this while testing MetaCPAN with the [Ladybird browser](https://github.com/SerenityOS/serenity) where is kindly spat out:
```
187047.691 WebContent(331600): Expected <li> current node, but had <div>
```
Which came from
```c++
// -> An end tag whose tag name is "li"
if (token.is_end_tag() && token.tag_name() == HTML::TagNames::li) {
// If the stack of open elements does not have an li element in list item scope, then this is a parse error; ignore the token.
if (!m_stack_of_open_elements.has_in_list_item_scope(HTML::TagNames::li)) {
log_parse_error();
return;
}
// Otherwise, run these steps:
// 1. Generate implied end tags, except for li elements.
generate_implied_end_tags(HTML::TagNames::li);
// 2. If the current node is not an li element, then this is a parse error.
if …
```
> Correctly close HTML <div> in release.tx

- package.json
yarn may now complain about the lack of a packageManager value
> add packageManager field to package.json

- Dockerfile
- servers/uwsgi.ini
Convert to using uwsgi by default. The command given is meant for use in a production environment. A development setup with be provided separately.
> Dockerfile: run with uwsgi rather than plackup

- .github/workflows/test.yml
- **We no longer need dpanfile.snapshot artifacts**
- **Add Devel::Cover to cpanfile**
- **Use Devel::Cover in CI**
> Add code coverage

- metacpan_web.conf
The perl code no longer needs to build any of the css or less, so it doesn't need any configuration for lessc.
> remove unused lessc_command option

- root/base.tx
- root/static/less/nav.less
PTS is now over and LPW is looking for attendees and sponsors after a five year break. w/r/t d34b6a969db7cf2edf7945b9561959352eab1ad1
> add LPW information to banner

- codecov.yml
Our tests are somewhat inconsistent in their coverage, so coverage can go down slightly even with unrelated changes. We also have untested code, and small tweaks will often be shown as a reduction in coverage.
Setting a 1% threshold will reduce friction on both of these cases. Any larger changes will still require an increase in coverage, so we should still trend upward over time.
> set a 1% theshold for coverage changes

- build-assets.mjs
- package-lock.json
- package.json
- root/static/less/style.less
- root/static/less/syntaxhighlighter-theme.less
- root/static/less/syntaxhighlighter.less
- root/static/scss/style.scss
The syntax highlighter theme is rather terrible, trying to do its own css reset with !important on everything. This makes it awful to do our own overrides of its behavior. It also tries to do things that are no longer relevant.
Vendor the parts of the syntax highlighter theme that we need, removing the !important tags. This allows our own code to be simplified as well.
> fix syntaxhighlighter styles

- lib/MetaCPAN/Middleware/Static.pm
- lib/MetaCPAN/Web.pm
- t/static-mounts.t
Surrogate-Control headers were being set for 404 responses for static files. This would cause Fastly to cache them indefinitely. During a deploy, there would be a period of time where new servers would link to js and css assets, which old servers would respond with 404s and get cached.
Fix the static file serving code to only set the Surrogate-Control headers for 2xx responses to prevent this. This ended up being a significant rewrite of the middleware.
> rewrite static middleware to correctly set headers

- lib/MetaCPAN/Web/RenderUtil.pm
- t/markdown.t
We do our own filtering of any user controlled markdown files, so it's safe to allow arbitrary HTML to be used. And we want raw HTML to be usable for user markdown and especially for our own markdown.
Enable the OPT_UNSAFE flag to allow raw HTML.
> allow raw HTML to be used in markdown

- root/base.tx
It was accidentally removed in d34b6a969db7cf2edf7945b9561959352eab1ad1.
Fixes #3104
> Restore fastly logo to the footer

- Dockerfile
Doing an audit fix during docker build makes the output more unpredictable. And we have dependabot in place to update the listed dependencies.
It also will cause errors for dependencies that it can't fix. We are using an older version of bootstrap, which has a XSS issue in it. But it doesn't impact us based on our use of bootstrap. We can't upgrade bootstrap without significant work, so for now we want to ignore this issue. npm audit doesn't provide any way to ignore specific dependencies.
> Remove audit fix during docker build

- lib/MetaCPAN/Web/Controller/Release.pm
- t/controller/release.t
> Return 404 for releases missing author, e.g. /release//File-Stat-Convert instead of a 500

- root/static/js/github.js
The popup for GitHub profiles on the author page displayed outdated links leading to 404 errors. The affected links have been updated to point to the new page addresses.
Resolves #3189.
> Fix incorrect links to GitHub pages

- docker-compose.yml
This should allow the compose file to be included in metacpan's docker-compose without conflicts.
> give docker compose containers names to disambiguate them from other services

- root/static/less/search.less
The magnifying glass icon is now centered vertically without relying on its absolute size. This ensures proper centering, regardless of the icon's dimensions.
Original:
Fixed:
> Fix alignment of magnifying glass in search input

- docker-compose.yml
Fixes and improves a few things for docker compose:
* Specify a shorter COLUMNS value to try to prevent wrapping when used with docker compose in the foreground.
* Add a watch option to rebuild the image when the cpanfile is updated.
* Add a dependency on web-asset-build to web-server. This means if you specifically run the web-service, you'll still properly get the assets built.
> docker compose improvements

- run-dev
Port 5000 is always in use on macOS, so use 8000 instead. 8000 matches what docker-compose uses.
> run-dev: use port 8000 by default

- Dockerfile
- lib/MetaCPAN/Web/Controller/Root.pm
- root/healthcheck.tx
- t/controller/healthcheck.t
Adds a healthcheck end point doing some rudimentary work that can be checked.
Adds health checks to the docker containers. These will be used by docker-compose. Kubernetes doesn't use the declared docker health checks, so it won't have any impact on production.
> Add docker healthcheck

- root/base.tx
I left the `<div>` there so it's easy to add the next ad there.
> Remove LPW ad

- Dockerfile
- lib/MetaCPAN/Web/View/Xslate.pm
- metacpan_web.conf
We were already deleting the xslate cache directory on startup, because it was having problems with refreshing the templates properly. And in a deployment, we don't have any permanent storage anyway. So we can just use a temp directory for the cache.
Since we aren't caching templates anymore, we no longer need the var directory.
Fixes #3215
> use temp directory for xslate cache

- root/static/js/pod2html.mjs
Elements that are part of a DocumentFragment don't seem to have a working outerHTML property in Chrome.
Fixes #3223.
> pod2html: fix rendering in chrome

- root/static/js/syntaxhighlighter.mjs
getClientRects returns an array, and its values are relative to the viewport. scrollIntoView is much easier to use for this.
> fix scrolling to highlighted lines on source view

- root/inc/contributors.tx
Hi Team,    
Please review the pull request, when you get time.
Contributor information is orphaned in sidebar.
https://metacpan.org/pod/perlimports
Many Thanks.
Best Regards,
Mohammad
> Proposed patch for issue 3044

- root/search.tx
- t/controller/search.t
Adds the number of search hits and some formatting to the top of the search page for #2907
> show search hits at page top

- root/inc/activity.tx
Hi Team,
Please review the small patch when you get time.
Added attribute "alt" with value "Activity Graph" to the img element.
https://metacpan.org/pod/Test2
Many Thanks.
Best Regards,
Mohammad
> Proposed patch for issue 3108

- .gitignore
- local/.gitignore
This exists so that this mapping doesn't prevent "docker compose up"
from running:
web-server:
volumes:
- '/app/local'
The purpose of this is to prevent an existing ./local from being mapped
into the container, since there could well be a mismatch between the
locally installed perl used for ./local and the perl which is available
in the container.
> Add a placeholder ./local dir

- .github/workflows/test.yml
- .gitignore
- bin/install-playwright
- e2e/home.spec.ts
- package-lock.json
- package.json
- playwright.config.ts
- **npm install --save-dev @playwright/test**
- **Add a script to install Playwright**
- **Add playwright config**
- **Add a very basic Playwright test**
- **Add Playwright testing to test workflow**
> Add a simple Playwright test

- lib/MetaCPAN/Web/Controller/Author.pm
- lib/MetaCPAN/Web/Model/API/Favorite.pm
Hi Team,
Please review this tricky one.    
Explicitly setting size to 500 to override the default size 250.
https://metacpan.org/author/SYP
Many Thanks.
Best Regards,
Mohammad
> Proposed patch for issue 3235

- README.md
The old instructions are not valid YAML.
> Change configuration file name

- lib/MetaCPAN/Web/View/Xslate.pm
On older deployments, the xslate cache would sometimes not correctly
detect new template files, leading to unpredictable errors. Purging of
the cache directory on startup was added to deal with this.
The normal deployment is now done with a docker container, so there is
nothing to clear out at startup. Additionally, the cache directory isn't
being configured to a static path, so it will always be using a newly
created temp directory. Clearing out the template cache is no longer
relevant, so it can be removed.
> xslate: don't try to remove cache dir

- .github/workflows/update-snapshot.yml
- cpanfile.forced
Use signed commits (created via the API) rather than needing to calculate the git user info for the bot.
Fail if fetching cpm doesn't work.
Use perl-actions/get-prereqs rather than a weird cpanm invocation to calculate the forced prereqs.
Install ExtUtils::MakeMaker as part of the forced dependencies to ensure consistency.
> snapshot update improvements

- root/about/sponsors.tx
This should have happened years ago. My bad!
> Add OpenCage to sponsor page

- root/plussers.tx
Sort of fixes #3378.
The plussers URL now more closely resembles the /dist/Form-Tiny/permissions endpoint, which also has no sidebar.
> Remove empty sidebar from plussers page
